# -*- coding: utf-8 -*-
"""
Definición de las 15 secciones del formulario "Manejo o Proceso" para el
reporte PDF — mismo formato/tipos que CROP_REPORT_SECTIONS/HANDLER_REPORT_SECTIONS.
Sacada directamente de FORM_SPEC_MANEJO_PROCESO.md y verificada contra los
`name` reales de views/osp_form_manejo_proceso.xml.

Nota: este formulario es nativo en español, pero los `label` de aquí abajo
también se dejan en español (son los que se imprimen en el PDF) — solo los
`key` (nombres de campo) y los tipos siguen la convención técnica en
inglés, igual que en los demás manifests.
"""

MANEJO_PROCESO_REPORT_SECTIONS = [
    {
        'title': 'Sección 1: Información General',
        'fields': [
            {'key': '1_applicant_type', 'label': 'Seleccione una opción', 'type': 'text'},
            {'key': '1a_org_name', 'label': '1a. Nombre de la Organización', 'type': 'text'},
            {'key': '1b_dba_name', 'label': '1b. Nombre de la finca (si aplica)', 'type': 'text'},
            {'key': '1c_address', 'label': '1c. Dirección', 'type': 'text'},
            {'key': '1d_city', 'label': '1d. Ciudad', 'type': 'text'},
            {'key': '1e_state', 'label': '1e. Estado', 'type': 'm2o_state'},
            {'key': '1f_zip', 'label': '1f. Código Postal', 'type': 'text'},
            {'key': '1g_country', 'label': '1g. País', 'type': 'm2o_country'},
            {'key': '1h_same_as_billing', 'label': '1h. Información de Facturación: Igual que la dirección física', 'type': 'checkbox'},
            {'key': '1h_billing_address', 'label': 'Dirección de Facturación', 'type': 'text'},
            {'key': '1h_billing_city', 'label': 'Ciudad de Facturación', 'type': 'text'},
            {'key': '1h_billing_state', 'label': 'Estado de Facturación', 'type': 'text'},
            {'key': '1h_billing_zip', 'label': 'CP de Facturación', 'type': 'text'},
            {'key': '1h_billing_country', 'label': 'País de Facturación', 'type': 'text'},
            {'key': '1i_legal_rep_name', 'label': '1i. Representante Legal — Nombre', 'type': 'text'},
            {'key': '1i_legal_rep_email', 'label': 'Representante Legal — Correo', 'type': 'text'},
            {'key': '1i_legal_rep_phone', 'label': 'Representante Legal — Teléfono', 'type': 'text'},
            {'key': '1j_contacts_json', 'label': '1j. Representantes Autorizados', 'type': 'table',
             'columns': [('name', 'Nombre'), ('email', 'Correo'), ('phone', 'Teléfono')]},
            {'key': '1k_legal_status', 'label': '1k. Estatus Legal de Organización', 'type': 'text'},
            {'key': '1k_legal_status_other', 'label': 'Otra (especifique)', 'type': 'text'},
            {'key': '1l_state_registration', 'label': '1l. ¿Cuenta con un registro Estatal?', 'type': 'yn'},
            {'key': '1l_state_reg_number', 'label': 'Número de registro Estatal (si aplica)', 'type': 'text'},
            {'key': '1l_certificate_attachment_needed', 'label': 'Adjunte copia de su certificado Estatal más actual', 'type': 'checkbox'},
            {'key': '1m_nop_standards_copy', 'label': '1m. ¿Tiene una copia de los estándares orgánicos actuales de NOP?', 'type': 'yn'},
            {'key': '1n_description', 'label': '1n. Descripción de las actividades en su operación', 'type': 'textarea'},
            {'key': '1o_months_production', 'label': '1o. Meses de producción', 'type': 'text'},
            {'key': '1p_business_hours', 'label': '1p. Horarios laborales', 'type': 'text'},
            {'key': '1q_inspection_language', 'label': '1q. Idioma de inspección de preferencia', 'type': 'text'},
            {'key': '1r_documentation_language', 'label': '1r. Idioma de documentación', 'type': 'text'},
            {'key': '1s_produce_or_handle', 'label': '1s. ¿Su operación produce o maneja?', 'type': 'text'},
            {'key': '1t_directions', 'label': '1t. Indicaciones de ubicación / GPS', 'type': 'textarea'},
            {'key': '1t_available_contact', 'label': '¿En qué horario se encuentra disponible para contactar?', 'type': 'text'},
            {'key': '1t_available_inspection', 'label': '¿En qué horario se encuentra disponible para la inspección?', 'type': 'text'},
            {'key': '1u_income_5000_or_less', 'label': '1u. ¿Ingreso agrícola bruto proyectado ≤ $5,000/año?', 'type': 'yn'},
            {'key': '1u_resell_as_organic', 'label': 'Si sí, ¿venderá a quien revenda como "orgánico"?', 'type': 'yn'},
            {'key': '1v_is_renewal', 'label': '1v. ¿Es renovación? ¿Cambió algo desde la última certificación?', 'type': 'yn'},
            {'key': '1v_changes_summary', 'label': 'Si sí, resuma los cambios', 'type': 'textarea'},
            {'key': '1w_self_audit', 'label': '1w. ¿Ha realizado una autoauditoría orgánica?', 'type': 'yn'},
            {'key': '1w_self_audit_date', 'label': 'Si sí, indique la fecha', 'type': 'date'},
        ],
    },
    {
        'title': 'Sección 2: Certificación Orgánica Previa y/o No Conformidades',
        'fields': [
            {'key': '2_na', 'label': 'No aplica esta sección a mi operación', 'type': 'checkbox'},
            {'key': '2a_denied_certification', 'label': '2a. ¿Alguna vez se le ha negado, suspendido o revocado la certificación?', 'type': 'yn'},
            {'key': '2a_certifier_and_docs', 'label': 'Si sí, certificador y documentación', 'type': 'textarea'},
            {'key': '2a_documentation_attachment_needed', 'label': 'Envíe toda la documentación', 'type': 'checkbox'},
            {'key': '2b_certified_elsewhere', 'label': '2b. ¿Certificada actualmente con otra agencia?', 'type': 'yn'},
            {'key': '2b_certificate_attachment_needed', 'label': 'Adjunte copia del certificado actual', 'type': 'checkbox'},
            {'key': '2c_previously_certified', 'label': '2c. ¿Alguna vez se ha certificado en orgánico la operación?', 'type': 'yn_na'},
            {'key': '2c_certificate_attachment_needed', 'label': 'Adjunte copia del certificado orgánico anterior', 'type': 'checkbox'},
            {'key': '2d_noncompliances_na', 'label': 'N/A, sin incumplimientos', 'type': 'checkbox'},
            {'key': '2d_noncompliances_details', 'label': '2d. Incumplimientos de la última certificación y cómo se abordaron', 'type': 'textarea'},
            {'key': '2d_documentation_attachment_needed', 'label': 'Adjunte documentación de incumplimientos resueltos', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Sección 3: Mercados Internacionales',
        'fields': [
            {'key': '3_na', 'label': 'No aplica esta sección a mi operación', 'type': 'checkbox'},
            {'key': '3a_market_types', 'label': '3a. Seleccione la opción que aplica', 'type': 'checkbox_group'},
        ],
    },
    {
        'title': 'Sección 4: Información de la Instalación y Productos',
        'fields': [
            {'key': '4a_operation_types', 'label': '4a. Tipo de operación (todas las que apliquen)', 'type': 'checkbox_group'},
            {'key': '4a_operation_types_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '4b_other_sites', 'label': '4b. ¿Gestiona otros sitios?', 'type': 'yn'},
            {'key': '4b_sites_json', 'label': 'Sitios', 'type': 'table',
             'columns': [('site_id', 'ID/Nombre'), ('site_address', 'Dirección'), ('city_state', 'Ciudad, Estado'),
                         ('zip_code', 'CP'), ('contact', 'Contacto'), ('description', 'Descripción')]},
            {'key': '4c_flow_diagram_attached', 'label': '4c. Diagrama de flujo adjunto', 'type': 'yn'},
            {'key': '4d_nonorganic_products_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '4d_nonorganic_products', 'label': '4d. Productos no-orgánicos manejados', 'type': 'textarea'},
            {'key': '4e_pct_nonorganic', 'label': '4e. % producción — No Orgánico', 'type': 'text'},
            {'key': '4e_pct_organic', 'label': '% producción — Orgánico', 'type': 'text'},
            {'key': '4f_other_certifications', 'label': '4f. ¿Otras certificaciones además de la orgánica?', 'type': 'yn'},
            {'key': '4f_other_certifications_details', 'label': 'Empresa auditora y esquema(s)', 'type': 'text'},
            {'key': '4g_uses_ingredients', 'label': '4g. ¿Usa/agrega ingredientes?', 'type': 'yn'},
            {'key': '4g_ingredients_list_attachment_needed', 'label': 'Presentar lista de ingredientes', 'type': 'checkbox'},
            {'key': '4h_contamination_prevention_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '4h_contamination_prevention', 'label': '4h. Prevención de contaminación/mezcla', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 5: Productos – Para ser Incluidos en el Certificado por Marca de Identificación y Mercado',
        'fields': [
            {'key': '5a_marketing_types', 'label': '5a. Tipo de mercado', 'type': 'checkbox_group'},
            {'key': '5a_marketing_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '5b_supply_chain_attached', 'label': '5b. Lista de cadena de suministro adjunta', 'type': 'yn'},
            {'key': '5c_list_all_id_marks', 'label': '5c. ¿Certificado debe listar todas las marcas?', 'type': 'yn'},
            {'key': '5d_products_json', 'label': '5d. Marcas de Identificación', 'type': 'table',
             'columns': [('product', 'Producto'), ('id_mark', 'Marca'), ('label_type', 'Tipo de Etiqueta'),
                         ('packing_with_id', '¿Empacará?'), ('organic_or_100', 'Orgánico/100%'), ('international_market', 'Mercados Internacionales')]},
        ],
    },
    {
        'title': 'Sección 6: Biodiversidad y Recursos Naturales',
        'fields': [
            {'key': '6a_biodiversity_program', 'label': '6a. Programa de biodiversidad', 'type': 'textarea'},
            {'key': '6b_natural_resources', 'label': '6b. Recursos naturales dentro/alrededor de la operación', 'type': 'textarea'},
            {'key': '6_water_use_na', 'label': 'Uso de Agua — N/A', 'type': 'checkbox'},
            {'key': '6c_water_source', 'label': '6c. Fuente de agua', 'type': 'text'},
            {'key': '6d_water_analysis_attached', 'label': '6d. Análisis de agua adjunto (fuente no municipal)', 'type': 'yn'},
            {'key': '6d_water_analysis_doc_name', 'label': 'Nombre del documento', 'type': 'text'},
            {'key': '6e_water_conservation', 'label': '6e. Prácticas de conservación de agua', 'type': 'textarea'},
            {'key': '6f_water_use_capacity', 'label': '6f. Actividad en que se usa el agua', 'type': 'text'},
            {'key': '6g_onsite_water_treatments', 'label': '6g. ¿Tratamientos de agua?', 'type': 'yn'},
            {'key': '6_boiler_na', 'label': 'Uso de la Caldera — N/A', 'type': 'checkbox'},
            {'key': '6h_steam_contact', 'label': '6h. ¿Vapor con contacto directo con productos orgánicos?', 'type': 'yn'},
            {'key': '6h_boiler_chemicals_used', 'label': '¿Usa químicos de caldera?', 'type': 'yn'},
            {'key': '6h_boiler_chemicals_attached', 'label': 'Lista de químicos en Lista de materiales. ¿Adjunta?', 'type': 'yn'},
            {'key': '6h_contamination_prevention', 'label': 'Cómo evita contaminación por químicos de caldera', 'type': 'textarea'},
            {'key': '6i_boiler_condensation_tested', 'label': '6i. ¿Se analiza la condensación de la caldera?', 'type': 'yn'},
            {'key': '6i_results_attachment_needed', 'label': 'Adjunte los resultados de los análisis', 'type': 'checkbox'},
            {'key': '6j_waste_management', 'label': '6j. Prácticas de gestión de residuos', 'type': 'textarea'},
            {'key': '6k_recycle_waste', 'label': '6k. ¿Recicla materiales de desecho?', 'type': 'yn'},
            {'key': '6k_recycle_describe', 'label': 'Describa', 'type': 'textarea'},
            {'key': '6l_energy_conservation', 'label': '6l. Prácticas de conservación de energía', 'type': 'textarea'},
            {'key': '6m_air_quality', 'label': '6m. Prácticas de calidad del aire', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 7: Mantenimiento de la Integridad Orgánica - Almacenamiento y Manejo Post Cosecha',
        'fields': [
            {'key': '7a_storage_areas', 'label': '7a. Zonas utilizadas para almacenamiento', 'type': 'textarea'},
            {
                'label': '7b. Almacenamiento', 'type': 'fixed_rows', 'prefix': '7b', 'row_header': 'Categoría',
                'columns': [('id_name', 'Identificación/Número'), ('type', 'Tipo'), ('dedicated_organic', 'Dedicado a Orgánico'),
                            ('offsite_used', 'Usado Fuera de Instalaciones'), ('capacity', 'Capacidad')],
                'rows': [
                    {'key': 'ingredients', 'label': 'Ingredientes'},
                    {'key': 'finished_goods', 'label': 'Productos Terminados'},
                    {'key': 'packaging_materials', 'label': 'Material de Empaque'},
                    {'key': 'other', 'label_key': '7b_other_label'},
                ],
            },
            {'key': '7c_shipping_form', 'label': '7c. Forma de envío de productos terminados', 'type': 'text'},
            {'key': '7d_packaging_material_type', 'label': '7d. Tipo de material de envase', 'type': 'text'},
            {'key': '7e_packaging_free_of_synthetics', 'label': '7e. ¿Empaque libre de sintéticos?', 'type': 'yn_na'},
            {'key': '7e_explain', 'label': 'Si no, explique', 'type': 'textarea'},
            {'key': '7e_evidence_attachment_needed', 'label': 'Adjunte evidencia documentada', 'type': 'checkbox'},
            {'key': '7f_water_used_postharvest', 'label': '7f. ¿Usa agua en manejo post-cosecha?', 'type': 'yn'},
            {'key': '7f_direct_contact', 'label': '¿Contacto directo con cultivos o superficies alimentarias?', 'type': 'yn'},
            {'key': '7f_water_documented', 'label': '¿Documentó cumplimiento de Ley de Agua Potable?', 'type': 'yn'},
            {'key': '7f_test_results_attachment_needed', 'label': 'Adjunte resultados del análisis', 'type': 'checkbox'},
            {'key': '7g_offsite_storage', 'label': '7g. ¿Productos almacenados fuera de sitio?', 'type': 'yn'},
        ],
    },
    {
        'title': 'Sección 8: Mantenimiento de la Integridad Orgánica – Equipo y Sanitización',
        'fields': [
            {'key': '8a_equipment_list', 'label': '8a. Equipos utilizados en la operación', 'type': 'textarea'},
            {'key': '8b_equipment_dedicated_organic', 'label': '8b. ¿Todo el equipo dedicado a orgánico?', 'type': 'yn'},
            {'key': '8b_prevention_practices', 'label': 'Si no, prácticas/barreras para prevenir mezcla', 'type': 'textarea'},
            {'key': '8c_equipment_cleaned', 'label': '8c. ¿Equipo limpiado/purgado antes de manejo orgánico?', 'type': 'yn_na'},
            {'key': '8d_cleaning_procedures', 'label': '8d. Procedimientos de limpieza de equipo', 'type': 'textarea'},
            {'key': '8e_personnel_measures', 'label': '8e. Medidas para proteger integridad orgánica', 'type': 'textarea'},
            {'key': '8f_sanitation_program', 'label': '8f. Programa de saneamiento', 'type': 'textarea'},
            {'key': '8_chlorine_na', 'label': 'Uso de Cloro — N/A', 'type': 'checkbox'},
            {'key': '8g_use_chlorine', 'label': '8g. ¿Usa cloro o productos con cloro?', 'type': 'yn'},
            {'key': '8h_chlorine_details', 'label': '8h. Propósito/formulación/dónde/cómo se usa', 'type': 'textarea'},
            {'key': '8i_chlorine_verification', 'label': '8i. Cómo verifica cumplimiento NOP de cloro', 'type': 'textarea'},
            {'key': '8j_commodities_sampled', 'label': '8j. ¿Se muestrean productos orgánicos?', 'type': 'yn'},
            {'key': '8j_tools_dedicated', 'label': '¿Herramientas de muestreo dedicadas a orgánico?', 'type': 'yn'},
            {'key': '8j_cleaning_description', 'label': 'Si no, cómo se limpia el equipo de muestreo', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 9: Mantenimiento de la Integridad Orgánica - Insumos',
        'fields': [
            {'key': '9a_inputs_json', 'label': '9a. Insumos', 'type': 'table',
             'columns': [('input_used_for', 'Uso'), ('brand_name', 'Marca comercial'), ('ingredients', 'Ingredientes'),
                         ('food_contact', '¿Contacto con alimentos?'), ('compliance_approval_by', 'Aprobación de conformidad por'),
                         ('label_docs_attached', 'Etiqueta/docs adjunta'), ('restrictions_description', 'Restricciones')]},
        ],
    },
    {
        'title': 'Sección 10: Mantenimiento de la Integridad Orgánica - Transporte',
        'fields': [
            {'key': '10a_responsible_for_transport', 'label': '10a. ¿Responsable del transporte?', 'type': 'yn'},
            {'key': '10b_receiving_method', 'label': '10b. Cómo se reciben los productos orgánicos', 'type': 'text'},
            {'key': '10c_shipping_method', 'label': '10c. Cómo se envían los productos orgánicos', 'type': 'text'},
            {'key': '10d_unsealed_or_reusable', 'label': '10d. ¿Recibe en envases permeables/reutilizables?', 'type': 'yn'},
            {'key': '10d_verification_methods', 'label': 'Cómo verifica que no se contaminó en tránsito', 'type': 'checkbox_group'},
            {'key': '10d_verification_methods_other', 'label': 'Especifique', 'type': 'text'},
        ],
    },
    {
        'title': 'Sección 11: Mantenimiento de la Integridad Orgánica - Envasado',
        'fields': [
            {'key': '11_na', 'label': 'No es aplicable a la operación', 'type': 'checkbox'},
            {'key': '11a_packaging_type', 'label': '11a. Tipo de envase/empaque', 'type': 'text'},
            {'key': '11b_food_grade', 'label': '11b. ¿Envases de grado alimenticio?', 'type': 'yn'},
            {'key': '11c_reused', 'label': '11c. ¿Se reutilizan los materiales de empaque?', 'type': 'yn'},
            {'key': '11c_previous_use', 'label': 'Si sí, uso anterior', 'type': 'textarea'},
            {'key': '11c_cleaning_procedure', 'label': 'Procedimiento de limpieza previo a reutilización', 'type': 'textarea'},
            {'key': '11d_free_of_synthetics', 'label': '11d. ¿Envases libres de sintéticos?', 'type': 'yn'},
            {'key': '11d_verification', 'label': 'Cómo se verifica', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 12: Mantenimiento de la Integridad Orgánica – Control de Plagas',
        'fields': [
            {'key': '12a_pest_control_responsible', 'label': '12a. Responsable del control de plagas', 'type': 'text'},
            {'key': '12a_contractor_info', 'label': 'Empresa contratada (nombre y número)', 'type': 'text'},
            {'key': '12b_pest_issues', 'label': '12b. ¿Problemas de plagas?', 'type': 'yn'},
            {'key': '12b_problem_pests', 'label': 'Si sí, plagas', 'type': 'textarea'},
            {'key': '12c_pest_controls', 'label': '12c. Controles de plagas', 'type': 'checkbox_group'},
            {'key': '12c_pest_controls_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '12d_prevention_strategies', 'label': '12d. Estrategias de prevención', 'type': 'textarea'},
            {'key': '12e_practices_documented', 'label': '12e. ¿Prácticas documentadas?', 'type': 'yn'},
            {'key': '12f_sufficiency_documented', 'label': '12f. ¿Documenta suficiencia de prácticas?', 'type': 'yn'},
            {'key': '12g_materials_in_processing_areas', 'label': '12g. ¿Materiales en áreas de proceso?', 'type': 'yn'},
            {'key': '12g_contamination_prevention', 'label': 'Si sí, procedimientos de prevención', 'type': 'textarea'},
            {'key': '12h_unlisted_materials_used', 'label': '12h. ¿Materiales no listados §205.605/606?', 'type': 'yn'},
            {'key': '12h_justification_documented', 'label': '¿Justificación/jerarquía documentada?', 'type': 'yn'},
            {'key': '12i_practices_documented_records', 'label': '12i. ¿Prácticas documentadas?', 'type': 'yn'},
            {'key': '12i_records_used', 'label': 'Registros usados', 'type': 'checkbox_group'},
            {'key': '12j_monitor_effectiveness', 'label': '12j. Monitoreo de efectividad', 'type': 'textarea'},
            {'key': '12k_effectiveness_rating', 'label': '12k. Calificación de efectividad', 'type': 'text'},
            {'key': '12l_anticipated_changes', 'label': '12l. Cambios previstos', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 13: Sistema de Mantenimiento de Registros',
        'fields': [
            {'key': '13a_traceback_description', 'label': '13a. Cómo los registros rastrean el producto', 'type': 'textarea'},
            {'key': '13b_lot_system', 'label': '13b. Sistema de numeración de lotes', 'type': 'textarea'},
            {'key': '13c_lot_number_packaging', 'label': '13c. Cómo asegura el número de lote en el envase', 'type': 'textarea'},
            {'key': '13d_claim_identification', 'label': '13d. ¿Registros identifican declaración aplicable?', 'type': 'yn'},
            {'key': '13d_claim_identification_details', 'label': 'Explique / detalle', 'type': 'textarea'},
            {'key': '13e_organic_records', 'label': '13e. Registros para producción orgánica', 'type': 'textarea'},
            {'key': '13f_records_5years', 'label': '13f. ¿Registros mantenidos 5+ años?', 'type': 'yn'},
            {'key': '13g_nonorganic_records', 'label': '13g. Registros para producción no-orgánica', 'type': 'checkbox_group'},
            {'key': '13g_nonorganic_records_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '13h_monitoring_practices', 'label': '13h. Prácticas de seguimiento', 'type': 'textarea'},
            {'key': '13i_monitoring_frequency', 'label': '13i. Cómo/frecuencia de implementación', 'type': 'textarea'},
            {'key': '13j_fraud_prevention_program', 'label': '13j. Programa de prevención de fraude', 'type': 'textarea'},
            {'key': '13k_fraud_prevention_docs', 'label': '13k. Documentos de prevención de fraude', 'type': 'textarea'},
            {'key': '13l_fraud_prevention_monitoring', 'label': '13l. Monitoreo de efectividad anti-fraude', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 14: Trazabilidad y Balance de Masas',
        'fields': [
            {'type': 'static', 'text': 'Sin campos — sección informativa que explica las auditorías de trazabilidad y balance de masas realizadas durante la inspección in situ.'},
        ],
    },
    {
        'title': 'Sección 15: Afirmación',
        'fields': [
            {'type': 'static', 'text': 'Yo afirmo que todas las declaraciones hechas en esta aplicación son verdaderas y correctas. Firma electrónica es aceptada.'},
            {'key': '15_name', 'label': 'Nombre del Representante Autorizado', 'type': 'text'},
            {'key': '15_signature', 'label': 'Firma del Representante Autorizado', 'type': 'text'},
            {'key': '15_date', 'label': 'Fecha', 'type': 'date'},
        ],
    },
]
