# -*- coding: utf-8 -*-
"""
Definición de las 10 secciones del formulario "Comercializador" para el
reporte PDF — mismo formato/tipos que los demás manifests. Sacada
directamente de FORM_SPEC_COMERCIALIZADOR.md y verificada contra los
`name` reales de views/osp_form_comercializador.xml. Formulario nativo en
español, equivalente de negocio de Handler (Trader).
"""

COMERCIALIZADOR_REPORT_SECTIONS = [
    {
        'title': 'Sección 1: Información General',
        'fields': [
            {'key': '1_applicant_type', 'label': 'Seleccione una opción', 'type': 'text'},
            {'key': '1a_org_name', 'label': '1a. Nombre de la Organización', 'type': 'text'},
            {'key': '1b_dba_name', 'label': '1b. Nombre de la finca (si aplica)', 'type': 'text'},
            {'key': '1c_address', 'label': '1c. Dirección', 'type': 'text'},
            {'key': '1d_city', 'label': '1d. Ciudad', 'type': 'text'},
            {'key': '1e_state', 'label': '1e. Estado', 'type': 'm2o_state'},
            {'key': '1f_zip', 'label': '1f. Código Postal', 'type': 'text'},
            {'key': '1g_country', 'label': '1g. País', 'type': 'm2o_country'},
            {'key': '1h_same_as_billing', 'label': '1h. Información de Facturación: Igual que la dirección física', 'type': 'checkbox'},
            {'key': '1h_billing_address', 'label': 'Dirección de Facturación', 'type': 'text'},
            {'key': '1h_billing_city', 'label': 'Ciudad de Facturación', 'type': 'text'},
            {'key': '1h_billing_state', 'label': 'Estado de Facturación', 'type': 'text'},
            {'key': '1h_billing_zip', 'label': 'CP de Facturación', 'type': 'text'},
            {'key': '1h_billing_country', 'label': 'País de Facturación', 'type': 'text'},
            {'key': '1i_legal_rep_name', 'label': '1i. Representante Legal — Nombre', 'type': 'text'},
            {'key': '1i_legal_rep_email', 'label': 'Representante Legal — Correo', 'type': 'text'},
            {'key': '1i_legal_rep_phone', 'label': 'Representante Legal — Teléfono', 'type': 'text'},
            {'key': '1j_contacts_json', 'label': '1j. Representantes Autorizados', 'type': 'table',
             'columns': [('name', 'Nombre'), ('email', 'Correo'), ('phone', 'Teléfono')]},
            {'key': '1k_legal_status', 'label': '1k. Estatus Legal de Organización', 'type': 'text'},
            {'key': '1k_legal_status_other', 'label': 'Otra (especifique)', 'type': 'text'},
            {'key': '1l_state_registration', 'label': '1l. ¿Cuenta con un registro Estatal?', 'type': 'yn'},
            {'key': '1l_state_reg_number', 'label': 'Número de registro Estatal (si aplica)', 'type': 'text'},
            {'key': '1l_certificate_attachment_needed', 'label': 'Adjunte copia de su certificado Estatal más actual', 'type': 'checkbox'},
            {'key': '1m_nop_standards_copy', 'label': '1m. ¿Tiene una copia de los estándares orgánicos actuales de NOP?', 'type': 'yn'},
            {'key': '1n_description', 'label': '1n. Descripción de las actividades en su operación', 'type': 'textarea'},
            {'key': '1o_months_production', 'label': '1o. Meses de producción', 'type': 'text'},
            {'key': '1p_business_hours', 'label': '1p. Horarios laborales', 'type': 'text'},
            {'key': '1q_inspection_language', 'label': '1q. Idioma de inspección de preferencia', 'type': 'text'},
            {'key': '1r_documentation_language', 'label': '1r. Idioma de documentación', 'type': 'text'},
            {'key': '1t_produce_or_handle', 'label': '1t. Qué produce o manipula su empresa', 'type': 'text'},
            {'key': '1u_directions', 'label': '1u. Indicaciones de ubicación / GPS', 'type': 'textarea'},
            {'key': '1u_available_contact', 'label': '¿En qué horario se encuentra disponible para contactar?', 'type': 'text'},
            {'key': '1u_available_inspection', 'label': '¿En qué horario se encuentra disponible para la inspección?', 'type': 'text'},
            {'key': '1v_income_5000_or_less', 'label': '1v. ¿Ingreso agrícola bruto proyectado ≤ $5,000/año?', 'type': 'yn'},
            {'key': '1v_resell_as_organic', 'label': 'Si sí, ¿venderá a quien revenda como "orgánico"?', 'type': 'yn'},
            {'key': '1w_is_renewal', 'label': '1w. ¿Es renovación? ¿Cambió algo desde la última certificación?', 'type': 'yn'},
            {'key': '1w_changes_summary', 'label': 'Si sí, resuma los cambios', 'type': 'textarea'},
            {'key': '1x_self_audit', 'label': '1x. ¿Ha realizado una auto auditoría orgánica?', 'type': 'yn'},
            {'key': '1x_self_audit_date', 'label': 'Si sí, indique la fecha', 'type': 'date'},
        ],
    },
    {
        'title': 'Sección 2: Certificación Orgánica Previa y/o Incumplimientos',
        'fields': [
            {'key': '2_na', 'label': 'No aplica esta sección a mi operación', 'type': 'checkbox'},
            {'key': '2a_denied_certification', 'label': '2a. ¿Se ha denegado, suspendido o revocado la certificación?', 'type': 'yn'},
            {'key': '2a_certifier_and_docs', 'label': 'Si sí, certificador y documentación', 'type': 'textarea'},
            {'key': '2a_documentation_attachment_needed', 'label': 'Facilite toda la documentación', 'type': 'checkbox'},
            {'key': '2b_certified_elsewhere', 'label': '2b. ¿Certificada actualmente con otra agencia?', 'type': 'yn'},
            {'key': '2b_certificate_attachment_needed', 'label': 'Adjunte copia del certificado actual', 'type': 'checkbox'},
            {'key': '2c_previously_certified', 'label': '2c. ¿Ha obtenido alguna vez la certificación orgánica?', 'type': 'yn_na'},
            {'key': '2c_certificate_attachment_needed', 'label': 'Adjunte copia del certificado orgánico anterior', 'type': 'checkbox'},
            {'key': '2d_noncompliances_na', 'label': 'N/A, sin incumplimientos', 'type': 'checkbox'},
            {'key': '2d_noncompliances_details', 'label': '2d. Incumplimientos de la última certificación y cómo se abordaron', 'type': 'textarea'},
            {'key': '2d_documentation_attachment_needed', 'label': 'Adjunte documentación de incumplimientos resueltos', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Sección 3: Mercados Internacionales',
        'fields': [
            {'key': '3_na', 'label': 'No aplica esta sección a mi operación', 'type': 'checkbox'},
            {'key': '3a_market_types', 'label': '3a. Seleccione la opción que aplica', 'type': 'checkbox_group'},
        ],
    },
    {
        'title': 'Sección 4: Información de la Operación',
        'fields': [
            {'key': '4a_other_sites', 'label': '4a. ¿Gestiona otros sitios?', 'type': 'yn'},
            {'key': '4a_sites_json', 'label': 'Sitios', 'type': 'table',
             'columns': [('site_id', 'ID/Nombre'), ('site_address', 'Dirección'), ('contact', 'Contacto'), ('description', 'Descripción')]},
            {'key': '4b_flow_diagram_attached', 'label': '4b. Diagrama de flujo adjunto', 'type': 'yn'},
            {'key': '4c_pct_nonorganic', 'label': '4c. % producción — No Orgánico', 'type': 'text'},
            {'key': '4c_pct_organic', 'label': '% producción — Orgánico', 'type': 'text'},
            {'key': '4c_nonorganic_list_attachment_needed', 'label': 'Presentar lista de productos no-orgánicos', 'type': 'checkbox'},
            {'key': '4d_other_certifications', 'label': '4d. ¿Otras certificaciones además de la orgánica?', 'type': 'yn'},
            {'key': '4d_other_certifications_details', 'label': 'Empresa auditora y esquema(s)', 'type': 'text'},
        ],
    },
    {
        'title': 'Sección 5: Productos – Para ser Incluidos en el Certificado por Marca de Identificación y Mercado',
        'fields': [
            {'key': '5a_marketing_types', 'label': '5a. Tipo de mercado', 'type': 'checkbox_group'},
            {'key': '5a_marketing_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '5b_supply_chain_attached', 'label': '5b. Lista de cadena de suministro adjunta', 'type': 'yn'},
            {'key': '5c_list_all_id_marks', 'label': '5c. ¿Certificado debe listar todas las marcas?', 'type': 'yn'},
            {'key': '5d_products_json', 'label': '5d. Marcas de Identificación', 'type': 'table',
             'columns': [('product', 'Producto'), ('id_mark', 'Marca'), ('label_type', 'Tipo de Etiqueta'),
                         ('organic_or_100', 'Orgánico/100%'), ('international_market', 'Mercados Internacionales')]},
        ],
    },
    {
        'title': 'Sección 6: Biodiversidad y Recursos Naturales',
        'fields': [
            {'key': '6a_biodiversity_program', 'label': '6a. Programa de biodiversidad', 'type': 'textarea'},
            {'key': '6b_natural_resources', 'label': '6b. Recursos naturales dentro/alrededor de la operación', 'type': 'textarea'},
            {'key': '6c_waste_management', 'label': '6c. Prácticas de gestión de residuos', 'type': 'textarea'},
            {'key': '6d_recycle_waste', 'label': '6d. ¿Recicla materiales de desecho?', 'type': 'yn'},
            {'key': '6d_recycle_describe', 'label': 'Describa', 'type': 'textarea'},
            {'key': '6e_energy_conservation', 'label': '6e. Prácticas de conservación de energía', 'type': 'textarea'},
            {'key': '6f_air_quality', 'label': '6f. Prácticas de calidad del aire', 'type': 'textarea'},
            {'key': '6g_water_source', 'label': '6g. Fuente de agua', 'type': 'text'},
            {'key': '6h_water_analysis_attached', 'label': '6h. Análisis de agua adjunto (fuente no municipal)', 'type': 'yn'},
            {'key': '6h_water_analysis_doc_name', 'label': 'Nombre del documento', 'type': 'text'},
            {'key': '6i_water_conservation', 'label': '6i. Prácticas de conservación de agua', 'type': 'textarea'},
            {'key': '6j_water_use_capacity', 'label': '6j. Actividad en que se usa el agua', 'type': 'text'},
        ],
    },
    {
        'title': 'Sección 7: Mantenimiento de la Integridad Orgánica',
        'fields': [
            {'key': '7_storage_na', 'label': 'Almacenamiento y Transporte — N/A', 'type': 'checkbox'},
            {'key': '7a_storage_operations', 'label': '7a. Operaciones utilizadas para almacenamiento', 'type': 'textarea'},
            {'key': '7b_responsible_for_transport', 'label': '7b. ¿Responsable del transporte del producto orgánico?', 'type': 'yn'},
            {'key': '7b_transport_company', 'label': 'Si sí, empresa', 'type': 'text'},
            {'key': '7c_receiving_form', 'label': '7c. Forma en que se reciben los productos orgánicos', 'type': 'text'},
            {'key': '7d_shipping_form', 'label': '7d. Forma en que se envían los productos terminados', 'type': 'text'},
            {'key': '7_quality_na', 'label': 'Pruebas de Calidad — N/A', 'type': 'checkbox'},
            {'key': '7e_products_sampled', 'label': '7e. ¿Se toman muestras/pruebas de calidad?', 'type': 'yn'},
            {'key': '7e_tools_dedicated', 'label': '¿Instrumentos de muestreo exclusivos para orgánico?', 'type': 'yn'},
            {'key': '7e_cleaning_description', 'label': 'Si no, limpieza del equipo de muestreo', 'type': 'textarea'},
            {'key': '7_packaging_na', 'label': 'Envasado/Empaquetado — N/A', 'type': 'checkbox'},
            {'key': '7f_packaging_material_type', 'label': '7f. Tipo de material de envasado', 'type': 'text'},
            {'key': '7g_free_of_synthetics', 'label': '7g. ¿Libre de fungicidas/conservantes/fumigantes sintéticos?', 'type': 'yn'},
            {'key': '7g_explain', 'label': 'Si no, explique', 'type': 'textarea'},
            {'key': '7g_evidence_attachment_needed', 'label': 'Adjunte pruebas documentadas', 'type': 'checkbox'},
            {'key': '7h_packaging_type', 'label': '7h. Tipo de envase utilizado', 'type': 'text'},
            {'key': '7i_food_grade', 'label': '7i. ¿Todos los envases son de grado alimenticio?', 'type': 'yn'},
            {'key': '7j_reused', 'label': '7j. ¿Se reutilizan materiales de empaque/contenedores?', 'type': 'yn_na'},
            {'key': '7j_previous_use', 'label': 'Si sí, uso anterior', 'type': 'textarea'},
            {'key': '7j_cleaning_procedure', 'label': 'Procedimiento de limpieza previo a reutilización', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 8: Sistema de Registro',
        'fields': [
            {'key': '8a_traceback_description', 'label': '8a. Cómo los registros rastrean el producto (trazabilidad)', 'type': 'textarea'},
            {'key': '8b_lot_tracking', 'label': '8b. Cómo el número de lote/envío vincula el producto con la documentación', 'type': 'textarea'},
            {'key': '8c_claim_identification', 'label': '8c. ¿Registros identifican declaración aplicable (100% orgánico, etc.)?', 'type': 'yn'},
            {'key': '8c_identification_explain', 'label': 'Si no, explique', 'type': 'textarea'},
            {'key': '8d_organic_records', 'label': '8d. Registros para producción orgánica', 'type': 'textarea'},
            {'key': '8e_records_5years', 'label': '8e. ¿Registros mantenidos 5+ años?', 'type': 'yn'},
            {'key': '8f_nonorganic_records', 'label': '8f. Registros para producción no-orgánica', 'type': 'checkbox_group'},
            {'key': '8f_nonorganic_records_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '8g_monitoring_practices', 'label': '8g. Prácticas de seguimiento', 'type': 'textarea'},
            {'key': '8h_monitoring_frequency', 'label': '8h. Cómo/frecuencia de implementación', 'type': 'textarea'},
            {'key': '8i_fraud_prevention_program', 'label': '8i. Programa de prevención de fraude orgánico', 'type': 'textarea'},
            {'key': '8j_fraud_prevention_docs', 'label': '8j. Documentos de prevención de fraude', 'type': 'textarea'},
            {'key': '8k_fraud_prevention_monitoring', 'label': '8k. Monitoreo de efectividad anti-fraude', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 9: Trazabilidad y Balance de Masas',
        'fields': [
            {'type': 'static', 'text': 'Sin campos — sección informativa que explica las auditorías de trazabilidad y balance de masas realizadas durante la inspección in situ.'},
        ],
    },
    {
        'title': 'Sección 10: Afirmación',
        'fields': [
            {'type': 'static', 'text': 'Yo afirmo que todas las declaraciones hechas en esta aplicación son verdaderas y correctas. Firma electrónica es aceptada.'},
            {'key': '10_name', 'label': 'Nombre del Representante Autorizado', 'type': 'text'},
            {'key': '10_signature', 'label': 'Firma del Representante Autorizado', 'type': 'text'},
            {'key': '10_date', 'label': 'Fecha', 'type': 'date'},
        ],
    },
]
