# -*- coding: utf-8 -*-
"""
Definición de las 10 secciones del formulario "Handler (Trader)" para el
reporte PDF — mismo formato/tipos que CROP_REPORT_SECTIONS/HANDLER_REPORT_SECTIONS.
Sacada directamente de FORM_SPEC_HANDLER_TRADER.md y verificada contra los
`name` reales de views/osp_form_handler_trader.xml.
"""

HANDLER_TRADER_REPORT_SECTIONS = [
    {
        'title': 'Section 1: General Information',
        'fields': [
            {'key': '1_applicant_type', 'label': 'Choose one', 'type': 'text'},
            {'key': '1a_org_name', 'label': '1a. Organization Name', 'type': 'text'},
            {'key': '1b_dba_name', 'label': '1b. dba Name (if applicable)', 'type': 'text'},
            {'key': '1c_address', 'label': '1c. Address', 'type': 'text'},
            {'key': '1d_city', 'label': '1d. City', 'type': 'text'},
            {'key': '1e_state', 'label': '1e. State', 'type': 'm2o_state'},
            {'key': '1f_zip', 'label': '1f. Zip code', 'type': 'text'},
            {'key': '1g_country', 'label': '1g. Country', 'type': 'm2o_country'},
            {'key': '1h_same_as_billing', 'label': '1h. Billing information: Same as Physical address', 'type': 'checkbox'},
            {'key': '1h_billing_address', 'label': 'Billing Address', 'type': 'text'},
            {'key': '1h_billing_city', 'label': 'Billing City', 'type': 'text'},
            {'key': '1h_billing_state', 'label': 'Billing State', 'type': 'text'},
            {'key': '1h_billing_zip', 'label': 'Billing Zip', 'type': 'text'},
            {'key': '1h_billing_country', 'label': 'Billing Country', 'type': 'text'},
            {'key': '1i_legal_rep_name', 'label': '1i. Legal Representative — Name', 'type': 'text'},
            {'key': '1i_legal_rep_email', 'label': 'Legal Representative — Email', 'type': 'text'},
            {'key': '1i_legal_rep_phone', 'label': 'Legal Representative — Phone', 'type': 'text'},
            {'key': '1j_contacts_json', 'label': '1j. Authorized Contacts', 'type': 'table',
             'columns': [('name', 'Name'), ('email', 'Email'), ('phone', 'Phone')]},
            {'key': '1k_legal_status', 'label': '1k. Organization Legal status', 'type': 'text'},
            {'key': '1k_legal_status_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '1l_state_registration', 'label': '1l. Do you obtain a State registration?', 'type': 'yn'},
            {'key': '1l_state_reg_number', 'label': 'State registration # (if applicable)', 'type': 'text'},
            {'key': '1l_certificate_attachment_needed', 'label': 'Attach a copy of your current State certificate', 'type': 'checkbox'},
            {'key': '1m_nop_standards_copy', 'label': '1m. Do you have a copy of current NOP organic standards?', 'type': 'yn'},
            {'key': '1n_description', 'label': "1n. Description of operation's activities", 'type': 'textarea'},
            {'key': '1o_months_production', 'label': '1o. Months of Production', 'type': 'text'},
            {'key': '1p_business_hours', 'label': '1p. Business hours', 'type': 'text'},
            {'key': '1q_inspection_language', 'label': '1q. Inspection language preference', 'type': 'text'},
            {'key': '1r_documentation_language', 'label': '1r. What language is your documentation?', 'type': 'text'},
            {'key': '1t_produce_or_handle', 'label': '1t. What does your operation produce or handle', 'type': 'text'},
            {'key': '1u_directions', 'label': '1u. Driving directions / GPS confirmation', 'type': 'textarea'},
            {'key': '1u_available_contact', 'label': 'When are you available to contact?', 'type': 'text'},
            {'key': '1u_available_inspection', 'label': 'When are you available for inspection?', 'type': 'text'},
            {'key': '1v_income_5000_or_less', 'label': "1v. Operation's projected gross agricultural income from organic sales ≤ $5,000/year?", 'type': 'yn'},
            {'key': '1v_resell_as_organic', 'label': 'If yes, do you intend to sell to anyone reselling as "organic"?', 'type': 'yn'},
            {'key': '1w_is_renewal', 'label': '1w. Is this a renewal? Has anything changed since your last certification?', 'type': 'yn'},
            {'key': '1w_changes_summary', 'label': 'If yes, summarize the changes', 'type': 'textarea'},
            {'key': '1x_self_audit', 'label': '1x. Have you conducted an organic self-audit?', 'type': 'yn'},
            {'key': '1x_self_audit_date', 'label': 'If yes, indicate the date', 'type': 'date'},
        ],
    },
    {
        'title': 'Section 2: Prior Organic Certification and/or Noncompliance',
        'fields': [
            {'key': '2_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '2a_denied_certification', 'label': '2a. Has this organization ever been denied certification, suspended or revoked?', 'type': 'yn'},
            {'key': '2a_certifier_and_docs', 'label': 'If yes, certifier name and documentation', 'type': 'textarea'},
            {'key': '2a_documentation_attachment_needed', 'label': 'Provide all documentation', 'type': 'checkbox'},
            {'key': '2b_certified_elsewhere', 'label': '2b. Is this organization currently certified organic with another agency?', 'type': 'yn'},
            {'key': '2b_certificate_attachment_needed', 'label': 'Attach a copy of your current organic certificate', 'type': 'checkbox'},
            {'key': '2c_previously_certified', 'label': '2c. For first time auditees, has this organization ever been certified organic?', 'type': 'yn_na'},
            {'key': '2c_certificate_attachment_needed', 'label': 'Attach a copy of your previous organic certificate', 'type': 'checkbox'},
            {'key': '2d_noncompliances_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '2d_noncompliances_details', 'label': '2d. Non-compliances from last certification and how addressed', 'type': 'textarea'},
            {'key': '2d_documentation_attachment_needed', 'label': 'Attach documentation that verified non-compliances have been addressed', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Section 3: International Markets',
        'fields': [
            {'key': '3_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '3a_market_types', 'label': '3a. Select all that applies', 'type': 'checkbox_group'},
        ],
    },
    {
        'title': 'Section 4: Operation Information',
        'fields': [
            {'key': '4a_other_sites', 'label': '4a. Do you manage other office sites other than the address in Section 1?', 'type': 'yn'},
            {'key': '4a_sites_json', 'label': 'Sites', 'type': 'table',
             'columns': [('site_id', 'Site/ID Name'), ('site_address', 'Address: City, State, Zip'),
                         ('contact', 'Contact'), ('description', 'Description')]},
            {'key': '4b_flow_diagram_attached', 'label': '4b. Operation Flow Diagram Attached', 'type': 'yn'},
            {'key': '4c_pct_nonorganic', 'label': '4c. Projected % of total production — Non-organic', 'type': 'text'},
            {'key': '4c_pct_organic', 'label': 'Projected % of total production — Organic', 'type': 'text'},
            {'key': '4c_nonorganic_list_attachment_needed', 'label': 'Submit a list of the non-organic product handled', 'type': 'checkbox'},
            {'key': '4d_other_certifications', 'label': '4d. Does your operation have any certifications besides Organic?', 'type': 'yn'},
            {'key': '4d_other_certifications_details', 'label': 'If yes, auditing company and scheme(s)', 'type': 'text'},
        ],
    },
    {
        'title': 'Section 5: Products – To Be Listed on Certificate by ID Mark & Market',
        'fields': [
            {'key': '5a_marketing_types', 'label': '5a. Type of Marketing — select all that apply', 'type': 'checkbox_group'},
            {'key': '5a_marketing_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '5b_supply_chain_attached', 'label': '5b. Master Supply Chain and Product List attached', 'type': 'yn'},
            {'key': '5c_list_all_id_marks', 'label': '5c. Do you require your organic certificate to list all ID Marks?', 'type': 'yn'},
            {'key': '5d_products_json', 'label': '5d. Products', 'type': 'table',
             'columns': [('product', 'Product'), ('id_mark', 'ID Mark'), ('label_type', 'Label Type'),
                         ('organic_or_100', 'Organic/100% Organic?'), ('international_market', 'International Market')]},
        ],
    },
    {
        'title': 'Section 6: Biodiversity & Natural Resources',
        'fields': [
            {'key': '6a_biodiversity_program', 'label': '6a. Biodiversity program', 'type': 'textarea'},
            {'key': '6b_natural_resources', 'label': '6b. Natural resources within/surrounding the operation', 'type': 'textarea'},
            {'key': '6c_waste_management', 'label': '6c. Waste management practices', 'type': 'textarea'},
            {'key': '6d_recycle_waste', 'label': '6d. Do you recycle waste materials?', 'type': 'yn'},
            {'key': '6d_recycle_describe', 'label': 'Describe', 'type': 'textarea'},
            {'key': '6e_energy_conservation', 'label': '6e. Energy conservation practices', 'type': 'textarea'},
            {'key': '6f_air_quality', 'label': '6f. Air quality management practices', 'type': 'textarea'},
            {'key': '6_water_use_na', 'label': 'Water Use — N/A', 'type': 'checkbox'},
            {'key': '6g_water_source', 'label': '6g. Water source', 'type': 'text'},
            {'key': '6h_water_analysis_attached', 'label': '6h. Water analysis attached (non-municipal source)', 'type': 'yn'},
            {'key': '6h_water_analysis_doc_name', 'label': 'Name of document', 'type': 'text'},
            {'key': '6i_water_conservation', 'label': '6i. Water conservation practices', 'type': 'textarea'},
            {'key': '6j_water_use_capacity', 'label': '6j. Water use capacity', 'type': 'text'},
        ],
    },
    {
        'title': 'Section 7: Maintenance of Organic Integrity',
        'fields': [
            {'key': '7_storage_na', 'label': 'Storage & Shipping — N/A', 'type': 'checkbox'},
            {'key': '7a_storage_operations', 'label': '7a. Operations utilized for storage', 'type': 'textarea'},
            {'key': '7b_responsible_for_transport', 'label': '7b. Responsible for the transportation of the organic product?', 'type': 'yn'},
            {'key': '7b_transport_company', 'label': 'If yes, company', 'type': 'text'},
            {'key': '7c_receiving_form', 'label': '7c. Form in which organic products are received', 'type': 'text'},
            {'key': '7d_shipping_form', 'label': '7d. Form in which finished products are shipped', 'type': 'text'},
            {'key': '7_quality_na', 'label': 'Quality Testing — N/A', 'type': 'checkbox'},
            {'key': '7e_products_sampled', 'label': '7e. Are products/ingredients sampled for quality or testing?', 'type': 'yn'},
            {'key': '7e_tools_dedicated', 'label': 'Are sampling tools dedicated for organic use only?', 'type': 'yn'},
            {'key': '7e_cleaning_description', 'label': 'If no, how sampling equipment is cleaned', 'type': 'textarea'},
            {'key': '7_packaging_na', 'label': 'Packaging — N/A', 'type': 'checkbox'},
            {'key': '7f_packaging_material_type', 'label': '7f. Type of packaging material used', 'type': 'text'},
            {'key': '7g_free_of_synthetics', 'label': '7g. Packaging free of synthetic fungicide/preservative/fumigant?', 'type': 'yn'},
            {'key': '7g_explain', 'label': 'If no, explain', 'type': 'textarea'},
            {'key': '7g_evidence_attachment_needed', 'label': 'Attach documented evidence', 'type': 'checkbox'},
            {'key': '7h_packaging_type', 'label': '7h. Type of packaging used', 'type': 'text'},
            {'key': '7i_food_grade', 'label': '7i. Is all packaging food grade?', 'type': 'yn'},
            {'key': '7j_reused', 'label': '7j. Are packaging materials/containers ever re-used?', 'type': 'yn_na'},
            {'key': '7j_previous_use', 'label': 'If yes, previous use', 'type': 'textarea'},
            {'key': '7j_cleaning_procedure', 'label': 'Cleaning procedure prior to reuse', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 8: Record-Keeping System',
        'fields': [
            {'key': '8a_traceback_description', 'label': '8a. How records track products (traceback)', 'type': 'textarea'},
            {'key': '8b_lot_tracking', 'label': '8b. How lot number/shipping ID links to audit trail', 'type': 'textarea'},
            {'key': '8c_claim_identification', 'label': '8c. Records identify applicable claim (100% organic, etc.)?', 'type': 'yn'},
            {'key': '8c_identification_explain', 'label': 'If no, explain', 'type': 'textarea'},
            {'key': '8d_organic_records', 'label': '8d. Records kept for organic production', 'type': 'textarea'},
            {'key': '8e_records_5years', 'label': '8e. Records maintained for 5+ years?', 'type': 'yn'},
            {'key': '8f_nonorganic_records', 'label': '8f. Records kept for non-organic production', 'type': 'checkbox_group'},
            {'key': '8f_nonorganic_records_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '8g_monitoring_practices', 'label': '8g. Monitoring practices/procedures', 'type': 'textarea'},
            {'key': '8h_monitoring_frequency', 'label': '8h. How/how frequently monitoring is implemented', 'type': 'textarea'},
            {'key': '8i_fraud_prevention_program', 'label': '8i. Organic fraud prevention program', 'type': 'textarea'},
            {'key': '8j_fraud_prevention_docs', 'label': '8j. Documents maintained for fraud prevention', 'type': 'textarea'},
            {'key': '8k_fraud_prevention_monitoring', 'label': '8k. How you monitor effectiveness of fraud prevention program', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 9: Trace back and Mass Balance',
        'fields': [
            {'type': 'static', 'text': 'No fields — informational section explaining trace-back and mass-balance audits performed during the on-site inspection.'},
        ],
    },
    {
        'title': 'Section 10: Affirmation',
        'fields': [
            {'type': 'static', 'text': 'I affirm that all statements made in this application are true and correct. No prohibited products have been applied to any of my organically managed fields during the three-year period prior to projected harvest. Electronic signature is accepted.'},
            {'key': '10_name', 'label': 'Name of Person completing this OSP', 'type': 'text'},
            {'key': '10_signature', 'label': 'Signature of Authorized Person', 'type': 'text'},
            {'key': '10_date', 'label': 'Date', 'type': 'date'},
        ],
    },
]
