# -*- coding: utf-8 -*-
"""
Definición de las 20 secciones del formulario "Crop" para el reporte PDF
(ir.actions.report). Es la ÚNICA fuente de verdad de qué preguntas
existen, en qué orden y de qué tipo son — el template QWeb del reporte
(report/osp_report_templates.xml) simplemente recorre esta estructura y
la formatea, en vez de tener ~2000 líneas de HTML repitiendo cada
pregunta a mano (igual que ya está construido el formulario web en
osp_form_crop.xml, del cual se sacaron uno a uno estos `key` — ver ese
archivo si hace falta verificar el key exacto de alguna pregunta).

Tipos soportados (ver _get_field_html en models/osp_request.py):
    text            input de una línea
    textarea        texto largo
    date            fecha
    yn              Sí/No (radio)
    yn_na           Sí/No/N-A (radio)
    checkbox        booleano único (se imprime como casilla + su propia etiqueta)
    checkbox_group  "selecciona todas las que apliquen" (lista de valores)
    m2o_state       Many2one a res.country.state (data.get(key) es un id)
    m2o_country     Many2one a res.country (data.get(key) es un id)
    table           tabla dinámica — 'columns': [(json_key, header), ...]
    static          texto fijo, sin campo (ej. Sección 17)

Si se agrega una pregunta nueva al formulario web, agregarla aquí
también para que aparezca en el PDF.
"""

CROP_REPORT_SECTIONS = [
    {
        'title': 'Section 1: General Information',
        'fields': [
            {'key': '1_applicant_type', 'label': 'Choose one', 'type': 'text'},
            {'key': '1a_org_name', 'label': '1a. Organization Name', 'type': 'text'},
            {'key': '1b_dba_name', 'label': '1b. dba Name (if applicable)', 'type': 'text'},
            {'key': '1c_address', 'label': '1c. Address', 'type': 'text'},
            {'key': '1d_city', 'label': '1d. City', 'type': 'text'},
            {'key': '1e_state', 'label': '1e. State', 'type': 'm2o_state'},
            {'key': '1f_zip', 'label': '1f. Zip code', 'type': 'text'},
            {'key': '1g_country', 'label': '1g. Country', 'type': 'm2o_country'},
            {'key': '1h_same_as_billing', 'label': '1h. Billing information: Same as Physical address', 'type': 'checkbox'},
            {'key': '1h_billing_address', 'label': 'Billing Address', 'type': 'text'},
            {'key': '1h_billing_city', 'label': 'Billing City', 'type': 'text'},
            {'key': '1h_billing_state', 'label': 'Billing State', 'type': 'text'},
            {'key': '1h_billing_zip', 'label': 'Billing Zip', 'type': 'text'},
            {'key': '1h_billing_country', 'label': 'Billing Country', 'type': 'text'},
            {'key': '1i_legal_rep_name', 'label': '1i. Legal Representative — Name', 'type': 'text'},
            {'key': '1i_legal_rep_email', 'label': 'Legal Representative — Email', 'type': 'text'},
            {'key': '1i_legal_rep_phone', 'label': 'Legal Representative — Phone', 'type': 'text'},
            {'key': '1j_contacts_json', 'label': '1j. Authorized Contacts', 'type': 'table',
             'columns': [('name', 'Name'), ('email', 'Email'), ('phone', 'Phone')]},
            {'key': '1k_legal_status', 'label': '1k. Organization Legal status', 'type': 'text'},
            {'key': '1k_legal_status_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '1l_state_registration', 'label': '1l. Do you obtain a State registration?', 'type': 'yn'},
            {'key': '1l_state_reg_number', 'label': 'State registration # (if applicable)', 'type': 'text'},
            {'key': '1l_certificate_attachment_needed', 'label': 'Attach a copy of your current State certificate', 'type': 'checkbox'},
            {'key': '1m_nop_standards_copy', 'label': '1m. Do you have a copy of current NOP organic standards?', 'type': 'yn'},
            {'key': '1n_description', 'label': "1n. Description of operation's activities", 'type': 'textarea'},
            {'key': '1o_months_production', 'label': '1o. Months of Production', 'type': 'text'},
            {'key': '1p_business_hours', 'label': '1p. Business hours', 'type': 'text'},
            {'key': '1q_inspection_language', 'label': '1q. Inspection language preference', 'type': 'text'},
            {'key': '1r_documentation_language', 'label': '1r. What language is your documentation?', 'type': 'text'},
            {'key': '1s_operation_type', 'label': '1s. Type of operation', 'type': 'text'},
            {'key': '1t_produce_or_handle', 'label': '1t. Does your operation produce or handle', 'type': 'text'},
            {'key': '1u_directions', 'label': '1u. Driving directions / GPS confirmation', 'type': 'textarea'},
            {'key': '1u_available_contact', 'label': 'When are you available to contact?', 'type': 'text'},
            {'key': '1u_available_inspection', 'label': 'When are you available for inspection?', 'type': 'text'},
            {'key': '1v_income_5000_or_less', 'label': "1v. Operation's projected gross agricultural income from organic sales ≤ $5,000/year?", 'type': 'yn'},
            {'key': '1v_resell_as_organic', 'label': 'If yes, do you intend to sell to anyone reselling as "organic"?', 'type': 'yn'},
            {'key': '1w_is_renewal', 'label': '1w. Is this a renewal? Has anything changed since your last certification?', 'type': 'yn'},
            {'key': '1w_changes_summary', 'label': 'If yes, summarize the changes', 'type': 'textarea'},
            {'key': '1x_self_audit', 'label': '1x. Have you conducted an organic self-audit?', 'type': 'yn'},
            {'key': '1x_self_audit_date', 'label': 'If yes, indicate the date', 'type': 'date'},
        ],
    },
    {
        'title': 'Section 2: Prior Organic Certification and/or Noncompliance',
        'fields': [
            {'key': '2_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '2a_denied_certification', 'label': '2a. Has this organization ever been denied certification, suspended or revoked?', 'type': 'yn'},
            {'key': '2a_denied_certifier_name', 'label': 'If yes, list the certifier name', 'type': 'text'},
            {'key': '2a_documentation_attachment_needed', 'label': 'Provide all documentation', 'type': 'checkbox'},
            {'key': '2b_certified_elsewhere', 'label': '2b. Is this organization currently certified organic with another agency?', 'type': 'yn'},
            {'key': '2b_certificate_attachment_needed', 'label': 'Attach a copy of your current organic certificate', 'type': 'checkbox'},
            {'key': '2c_previously_certified', 'label': '2c. For first time auditees, has this organization ever been certified organic?', 'type': 'yn_na'},
            {'key': '2c_certificate_attachment_needed', 'label': 'Attach a copy of your previous organic certificate', 'type': 'checkbox'},
            {'key': '2d_noncompliances_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '2d_noncompliances_details', 'label': '2d. List all non-compliances from your last certification and how they were addressed — Non-Compliances', 'type': 'textarea'},
            {'key': '2d_documentation_attachment_needed', 'label': 'Attach documentation that verified non-compliances have been addressed', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Section 3: International Markets',
        'fields': [
            {'key': '3_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '3a_market_types', 'label': '3a. Select all that applies', 'type': 'checkbox_group'},
        ],
    },
    {
        'title': 'Section 4: Crops & Fields',
        'fields': [
            {'key': '4a_producer_group', 'label': '4a. Are the requested areas or sites part of a Producer Group?', 'type': 'yn'},
            {'key': '4b_growers_list_attached', 'label': '4b. Attach a list of all growers within the group. Is the Producer Group list attached?', 'type': 'yn'},
            {'key': '4c_other_agency_certified', 'label': '4c. Have any of the sites/areas been certified by any other certification agency?', 'type': 'yn'},
            {'key': '4c_previous_agency_name', 'label': 'If yes, list previous organic certification agency', 'type': 'text'},
            {'key': '4d_noncompliances_open', 'label': '4d. Are there any minor or non compliances open?', 'type': 'yn'},
            {'key': '4d_info_attached', 'label': 'If yes, is the information attached?', 'type': 'yn'},
            {'key': '4e_ics_list_attached', 'label': '4e. Submit a list of all ICS non-compliances from the last annual visit. Is the list attached?', 'type': 'yn'},
            {'key': '4f_nonorganic_products', 'label': '4f. List of all non-organic products and where they are being grown', 'type': 'textarea'},
            {'key': '4g_sites_json', 'label': '4g. Sites', 'type': 'table',
             'columns': [('site_id', 'Site ID/Name'), ('site_address', 'Site Address'), ('city_state', 'City, State'),
                         ('zip', 'Zip'), ('contact', 'Contact'), ('description', 'Description')]},
            {'key': '4h_fields_json', 'label': '4h. Fields', 'type': 'table',
             'columns': [('field_id', 'Field ID'), ('parcel_address', 'Parcel Address'), ('area_type', 'Area Type'),
                         ('units', 'Units'), ('rented_or_owned', 'Rented/Owned')]},
            {'key': '4i_same_field_ids', 'label': '4i. Do you use these same field IDs in your record-keeping system?', 'type': 'yn'},
            {'key': '4i_explain', 'label': 'If no, explain', 'type': 'textarea'},
            {'key': '4j_crops_json', 'label': '4j. Crops', 'type': 'table',
             'columns': [('crop_requested', 'Crop Requested'), ('field_id', 'Field ID'), ('total_planted_area', 'Total Planted Area'),
                         ('area_units', 'Area Units'), ('projected_yield', 'Projected Yield'), ('yield_units', 'Yield Units')]},
        ],
    },
    {
        'title': 'Section 5: Products',
        'fields': [
            {'key': '5a_marketing_types', 'label': '5a. Type of Marketing — Select all that apply', 'type': 'checkbox_group'},
            {'key': '5a_marketing_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '5b_supply_chain_attached', 'label': '5b. Master Supply Chain and Product List — Is this document attached?', 'type': 'yn'},
            {'key': '5c_list_all_id_marks', 'label': '5c. Do you require your organic certificate to list all ID Marks?', 'type': 'yn'},
            {'key': '5d_products_json', 'label': '5d. Products', 'type': 'table',
             'columns': [('product', 'Product Requested'), ('id_mark', 'ID Mark'), ('label_type', 'Label Type'),
                         ('packing_with_id', 'Packing w/ ID?'), ('organic_or_100', 'Organic/100%'), ('international_market', 'Intl Market')]},
        ],
    },
    {
        'title': 'Section 6: Biodiversity & Natural Resources',
        'fields': [
            {'key': '6a_soil_conservation', 'label': '6a. What soil conservation practices are used?', 'type': 'textarea'},
            {'key': '6b_erosion_problems', 'label': '6b. What soil erosion problems do you experience?', 'type': 'textarea'},
            {'key': '6c_erosion_mitigation', 'label': '6c. Efforts to minimize soil erosion / monitoring', 'type': 'textarea'},
            {'key': '6d_natural_resources', 'label': '6d. Natural resources within/surrounding your operation', 'type': 'textarea'},
            {'key': '6e_woodland_na', 'label': 'N/A (woodland)', 'type': 'checkbox'},
            {'key': '6e_woodland_details', 'label': '6e. Are there woodland areas? Describe, if any', 'type': 'textarea'},
            {'key': '6f_wetlands_na', 'label': 'N/A (wetlands)', 'type': 'checkbox'},
            {'key': '6f_wetlands_details', 'label': '6f. Are there wetlands? Describe, if any', 'type': 'textarea'},
            {'key': '6g_wildlife_na', 'label': 'N/A (wildlife)', 'type': 'checkbox'},
            {'key': '6g_wildlife_details', 'label': '6g. Are there wildlife/biodiversity? Describe, if any', 'type': 'textarea'},
            {'key': '6h_water_source', 'label': '6h. What is your source of water?', 'type': 'text'},
            {'key': '6i_water_use', 'label': '6i. What is water used for at your operation?', 'type': 'text'},
            {'key': '6j_irrigation_type', 'label': '6j. What type of irrigation system is used?', 'type': 'text'},
            {'key': '6k_water_cleaning', 'label': '6k. Water system cleaning process / inputs used', 'type': 'textarea'},
            {'key': '6l_shared_system', 'label': '6l. Is the system shared with another operator?', 'type': 'yn'},
            {'key': '6l_shared_products', 'label': 'If yes, what products do they use?', 'type': 'text'},
            {'key': '6m_water_quality_practices', 'label': '6m. What practices are used to protect water quality?', 'type': 'textarea'},
            {'key': '6n_water_testing', 'label': '6n. Do you have a water testing program in place? Describe', 'type': 'textarea'},
            {'key': '6n_test_results_attachment_needed', 'label': 'Attach residue analysis and/or salinity test results, if applicable', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Section 7: Land requirements',
        'fields': [
            {'key': '7a_field_history_attached', 'label': '7a. Field History and supporting documents attached?', 'type': 'yn'},
            {'key': '7a_updated_map_attached', 'label': 'Updated Map attached?', 'type': 'yn'},
            {'key': '7b_managed_3years', 'label': '7b. Have you managed all fields for 3 or more years?', 'type': 'yn'},
            {'key': '7b_statements_attachment_needed', 'label': 'Submit signed statements from the previous land management owner', 'type': 'checkbox'},
            {'key': '7c_evidence_no_prohibited', 'label': '7c. Evidence that no prohibited substance has been used in the previous 3 years', 'type': 'textarea'},
            {'key': '7d_boundaries_defined', 'label': "7d. Are all fields' boundaries distinguishable and accurately reflected in maps?", 'type': 'yn'},
            {'key': '7e_acreage_consistent', 'label': '7e. Is field/crop acreage consistent among maps, histories and this OSP?', 'type': 'yn'},
            {'key': '7f_buffer_zones', 'label': '7f. Have you established buffer zones?', 'type': 'text'},
            {'key': '7f_buffer_zones_explain', 'label': 'Explain your answer / describe your buffer zones', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 8: Seeds & Planting Stock (Annual / Perennial)',
        'fields': [
            {'key': '8a_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '8a_seeds_json', 'label': '8a. Seeds', 'type': 'table',
             'columns': [('crop_variety', 'Crop/Variety'), ('brand_supplier', 'Brand/Supplier'), ('seed_type', 'Type'),
                         ('non_organic_treatment', 'Treatment (if non-organic)'), ('non_gmo_documented', 'Non-GMO Documented?'),
                         ('seed_search_form_completed', 'Search Form Completed?')]},
            {'key': '8a_seeds_attachment_needed', 'label': 'Submit supporting documents for the seeds listed above', 'type': 'checkbox'},
            {'key': '8b_organic_seedlings', 'label': '8b. Do you grow organic seedlings on-farm?', 'type': 'yn_na'},
            {'key': '8c_seedling_procedures', 'label': '8c. Steps and procedures carried out', 'type': 'textarea'},
            {'key': '8d_watering_equipment', 'label': '8d. Watering system equipment', 'type': 'textarea'},
            {'key': '8e_disease_prevention', 'label': '8e. Seedling disease/insect prevention', 'type': 'textarea'},
            {'key': '8f_additional_services', 'label': '8f. Additional services relating to seedlings or planting stock?', 'type': 'yn_na'},
            {'key': '8f_additional_services_describe', 'label': 'If yes, describe', 'type': 'textarea'},
            {'key': '8g_na', 'label': 'Planting stock section not applicable to my operation', 'type': 'checkbox'},
            {'key': '8g_planting_stock_json', 'label': '8g. Planting stock for perennial crops', 'type': 'table',
             'columns': [('type_crop_variety', 'Type (Crop-Variety)'), ('source_supplier', 'Source/Supplier'), ('seedling_type', 'Type'),
                         ('date_planted', 'Date Planted'), ('expected_harvest_date', 'Expected Harvest'), ('search_form_attached', 'Search Form?')]},
        ],
    },
    {
        'title': 'Section 9: Soil and Crop Fertility Management',
        'fields': [
            {'key': '9_general_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '9a_soil_types', 'label': '9a. General soil types', 'type': 'textarea'},
            {'key': '9b_soil_limitations', 'label': '9b. Main soil chemical/physical/biological limitations', 'type': 'textarea'},
            {'key': '9c_fertility_practices', 'label': '9c. Practices to improve/maintain soil fertility', 'type': 'textarea'},
            {'key': '9d_monitor_effectiveness', 'label': '9d. How do you monitor effectiveness of your fertility program?', 'type': 'textarea'},
            {'key': '9d_test_results_attachment_needed', 'label': 'Attach copies of available test results', 'type': 'checkbox'},
            {'key': '9e_effectiveness_rating', 'label': '9e. Rate the effectiveness of your fertility management program', 'type': 'text'},
            {'key': '9e_anticipated_changes', 'label': 'What changes do you anticipate?', 'type': 'textarea'},
            {'key': '9_composting_na', 'label': 'On-Farm Composting section not applicable to my operation', 'type': 'checkbox'},
            {'key': '9f_compost_ingredients', 'label': '9f. Compost ingredients/additives and proportion', 'type': 'textarea'},
            {'key': '9g_composting_method', 'label': '9g. Composting method', 'type': 'textarea'},
            {'key': '9h_cn_ratio', 'label': '9h. Initial C:N ratio', 'type': 'text'},
            {'key': '9i_compost_temp_maintained', 'label': '9i. Compost temp maintained 131-170°F for 15+ consecutive days?', 'type': 'yn'},
            {'key': '9_manure_na', 'label': 'Manure Use section not applicable to my operation', 'type': 'checkbox'},
            {'key': '9j_manure_forms', 'label': '9j. What forms of manure do you use?', 'type': 'checkbox_group'},
            {'key': '9j_manure_forms_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '9k_crop_types', 'label': '9k. What types of crops do you grow?', 'type': 'checkbox_group'},
            {'key': '9k_documentation_attachment_needed', 'label': 'If growing for human consumption + raw manure: submit supporting documentation', 'type': 'checkbox'},
            {'key': '9l_manure_source', 'label': '9l. Source of manure used', 'type': 'text'},
            {'key': '9m_offfarm_manure_sources', 'label': '9m. Sources of off-farm manure', 'type': 'textarea'},
            {'key': '9n_manure_ingredients', 'label': '9n. Manure ingredients/additives', 'type': 'textarea'},
            {'key': '9o_manure_contaminants', 'label': '9o. Potential contaminants from manure sources', 'type': 'textarea'},
            {'key': '9o_analysis_attachment_needed', 'label': 'Attach residue analysis/additive specifications for manure, if available', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Section 10: Crop Rotation',
        'fields': [
            {'key': '10_rotation_json', 'label': 'Crop Rotation Plans', 'type': 'table',
             'columns': [('rotation_plan', 'Rotation Plan'), ('objectives', 'Objectives')]},
        ],
    },
    {
        'title': 'Section 11: Crop pest, weed and disease management',
        'fields': [
            {'key': '11a_weed_disease_problems', 'label': '11a. Weed/disease problems and control methods', 'type': 'textarea'},
            {'key': '11b_restricted_strategy', 'label': '11b. Restricted weed/disease management strategy used', 'type': 'textarea'},
            {'key': '11c_mulch_removed', 'label': '11c. If mulch is used, is it removed at end of season?', 'type': 'yn_na'},
            {'key': '11c_mulch_not_removed_reason', 'label': 'If no, why not?', 'type': 'textarea'},
            {'key': '11d_pest_problems', 'label': '11d. Pest/disease problems and prevention strategies', 'type': 'textarea'},
            {'key': '11e_practices_documented', 'label': '11e. Are these preventive practices documented?', 'type': 'yn'},
            {'key': '11f_insufficiency_documented', 'label': '11f. Documented preventive practices were insufficient before applying substance?', 'type': 'yn'},
            {'key': '11f_describe', 'label': 'Describe briefly', 'type': 'textarea'},
            {'key': '11g_monitor_effectiveness', 'label': '11g. How do you monitor program effectiveness?', 'type': 'textarea'},
            {'key': '11h_effectiveness_rating', 'label': '11h. Rate the effectiveness of your weed/pest/disease management program', 'type': 'text'},
            {'key': '11i_anticipated_changes', 'label': '11i. What changes do you anticipate?', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 12: Maintenance of Organic Integrity – Inputs',
        'fields': [
            {'key': '12a_inputs_json', 'label': '12a. Inputs', 'type': 'table',
             'columns': [('input_used_for', 'Used For'), ('brand_name', 'Brand Name'), ('ingredients', 'Ingredients'),
                         ('compliance_approval_by', 'Compliance Approval By'), ('label_compliance_docs_attached', 'Docs Attached?'),
                         ('restrictions_compliance_description', 'NOP Annotation Compliance')]},
            {'key': '12b_storage_na', 'label': 'N/A (storage)', 'type': 'checkbox'},
            {'key': '12b_storage_description', 'label': '12b. Storage area for inputs', 'type': 'textarea'},
            {'key': '12c_prevention_practices', 'label': '12c. Practices/barriers to prevent commingling/contamination of inputs', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 13: Maintenance of Organic Integrity – Buffer Areas & Split Production',
        'fields': [
            {'key': '13_buffer_na', 'label': 'Buffer Areas section not applicable to my operation', 'type': 'checkbox'},
            {'key': '13a_risk_assessment', 'label': '13a. Frequency of risk assessment and current contamination risks', 'type': 'textarea'},
            {'key': '13b_buffer_description', 'label': '13b. Main buffer areas — size and other features', 'type': 'textarea'},
            {'key': '13c_buffer_validated', 'label': '13c. Have you validated your buffer areas are sufficient?', 'type': 'yn'},
            {'key': '13d_buffer_sufficient_explain', 'label': '13d. Explain why your buffer areas are sufficient', 'type': 'textarea'},
            {'key': '13e_maps_updated', 'label': '13e. Have you shown/updated adjoining land use and buffer zones in your maps?', 'type': 'yn'},
            {'key': '13f_buffer_harvest_use', 'label': '13f. Use of crop harvested from buffer areas', 'type': 'textarea'},
            {'key': '13g_buffer_harvest_safeguards', 'label': '13g. Safeguards during harvest in buffer zones', 'type': 'textarea'},
            {'key': '13h_safeguards', 'label': '13h. Additional safeguards to prevent accidental contamination', 'type': 'checkbox_group'},
            {'key': '13h_safeguards_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '13i_no_spray_signs', 'label': '13i. Have you posted "No Spray" signs along adjacent roadsides?', 'type': 'yn'},
            {'key': '13j_fields_flood', 'label': '13j. Do any fields flood frequently (more than once every 5 years)?', 'type': 'yn'},
            {'key': '13j_flood_field_numbers', 'label': 'If yes, list field numbers', 'type': 'text'},
            {'key': '13_split_na', 'label': 'Split Production section not applicable to my operation', 'type': 'checkbox'},
            {'key': '13k_contamination_prevention', 'label': '13k. Practices/barriers to prevent contamination of organic crops (non-organic growers)', 'type': 'textarea'},
            {'key': '13l_same_variety_mixed', 'label': '13l. Do you grow the same variety organically, in transition, and/or non-organically?', 'type': 'yn'},
            {'key': '13l_commingling_prevention', 'label': 'If yes, practices/barriers to prevent commingling', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 14: Maintenance of Organic Integrity – Equipment & Harvest',
        'fields': [
            {'key': '14_equipment_na', 'label': 'Equipment section not applicable to my operation', 'type': 'checkbox'},
            {'key': '14a_equipment_json', 'label': '14a. Equipment', 'type': 'table',
             'columns': [('equipment_name_model_code', 'Equipment Name/Model/Code'), ('owned_rented_custom', 'Owned/Rented/Custom'),
                         ('used_for', 'Used For'), ('cleaning_method', 'Cleaning Method')]},
            {'key': '14_harvest_na', 'label': 'Harvest section not applicable to my operation', 'type': 'checkbox'},
            {'key': '14b_harvest_method', 'label': '14b. How are your organic crops harvested?', 'type': 'checkbox_group'},
            {'key': '14b_harvest_description', 'label': 'Briefly provide a description', 'type': 'textarea'},
            {'key': '14c_subcontract_harvest', 'label': '14c. Do you subcontract harvesting labor?', 'type': 'yn'},
            {'key': '14c_subcontractor_info', 'label': 'If yes, name and address of custom-harvester', 'type': 'text'},
            {'key': '14d_subcontractor_training', 'label': '14d. Training of subcontracted labor for organic protocols', 'type': 'textarea'},
            {'key': '14e_containers_used', 'label': '14e. Containers used for harvesting', 'type': 'text'},
            {'key': '14f_containers_condition', 'label': '14f. Are containers new or used?', 'type': 'text'},
            {'key': '14f_previous_contents', 'label': 'If used, what did they contain prior to organic use?', 'type': 'text'},
            {'key': '14g_containers_organic_only', 'label': '14g. Are containers used for organic crops only?', 'type': 'yn'},
            {'key': '14h_contamination_problems', 'label': '14h. Contamination/commingling problems with harvest', 'type': 'textarea'},
            {'key': '14i_protection_steps', 'label': '14i. Steps to protect crops from commingling/contamination during harvest', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 15: Post-Harvest Handling, Storage and Transportation',
        'fields': [
            {'key': '15_handling_na', 'label': 'Post-Harvest Handling section not applicable to my operation', 'type': 'checkbox'},
            {'key': '15a_handling_procedures', 'label': '15a. Post-harvest handling procedures and equipment', 'type': 'textarea'},
            {'key': '15a_diagrams_attachment_needed', 'label': 'Attach a flow chart and a floor plan', 'type': 'checkbox'},
            {'key': '15b_shared_handling', 'label': '15b. Is the handling area/equipment used for both organic and non-organic?', 'type': 'yn'},
            {'key': '15b_prevention_steps', 'label': 'If yes, steps to prevent commingling/contamination', 'type': 'textarea'},
            {'key': '15c_shipping_form', 'label': '15c. Form in which finished products are shipped', 'type': 'text'},
            {'key': '15d_packaging_materials', 'label': '15d. Types of packaging material used', 'type': 'text'},
            {'key': '15e_packaging_documentation', 'label': '15e. Documentation that packaging is free of synthetic fungicide/preservative/fumigant', 'type': 'textarea'},
            {'key': '15e_evidence_attachment_needed', 'label': 'Attach documented evidence', 'type': 'checkbox'},
            {'key': '15f_water_used', 'label': '15f. Do you use water in post-harvest handling?', 'type': 'yn_na'},
            {'key': '15g_water_direct_contact', 'label': '15g. If yes, direct contact with crop/food surfaces?', 'type': 'yn'},
            {'key': '15h_water_documented', 'label': '15h. If yes, documented that water meets Safe Drinking Water Act?', 'type': 'yn'},
            {'key': '15_storage_na', 'label': 'Storage section not applicable to my operation', 'type': 'checkbox'},
            {'key': '15i_storage_id', 'label': 'Storage Identification', 'type': 'text'},
            {'key': '15i_storage_crop_type', 'label': 'Type of Crop', 'type': 'text'},
            {'key': '15i_storage_type', 'label': 'Type of Storage', 'type': 'text'},
            {'key': '15i_storage_capacity', 'label': 'Capacity', 'type': 'text'},
            {'key': '15i_storage_used_for', 'label': 'Used for', 'type': 'text'},
            {'key': '15j_shared_storage', 'label': '15j. Same storage areas for organic/transitional/buffer/non-organic?', 'type': 'yn'},
            {'key': '15j_segregation_method', 'label': 'If yes, how do you segregate organic from non-organic?', 'type': 'textarea'},
            {'key': '15k_storage_cleaning', 'label': '15k. Cleaning of storage units prior to organic crop storage', 'type': 'textarea'},
            {'key': '15l_pest_control_storage', 'label': '15l. Pest/rodent control in storage areas', 'type': 'textarea'},
            {'key': '15m_offsite_storage', 'label': '15m. Are goods ever stored at an offsite warehouse?', 'type': 'yn'},
            {'key': '15_transport_na', 'label': 'Transportation section not applicable to my operation', 'type': 'checkbox'},
            {'key': '15n_transport_responsible', 'label': '15n. Who is responsible for arranging transportation?', 'type': 'text'},
            {'key': '15n_transport_responsible_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '15o_transport_method', 'label': '15o. How organic products are transported', 'type': 'textarea'},
            {'key': '15p_transport_contamination_problems', 'label': '15p. Contamination/commingling problems in transport', 'type': 'textarea'},
            {'key': '15q_transport_protection_steps', 'label': '15q. Steps to protect integrity during transport', 'type': 'checkbox_group'},
            {'key': '15q_transport_protection_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '15_chlorine_na', 'label': 'Use of Chlorine section not applicable to my operation', 'type': 'checkbox'},
            {'key': '15r_use_chlorine', 'label': '15r. Do you use chlorine or chlorine containing products?', 'type': 'yn'},
            {'key': '15r_chlorine_details', 'label': 'If yes, purpose, formulation, where/how used', 'type': 'textarea'},
            {'key': '15r_label_attachment_needed', 'label': 'Attach label', 'type': 'checkbox'},
            {'key': '15s_chlorine_verification', 'label': '15s. Verification/documentation of chlorine NOP compliance', 'type': 'textarea'},
            {'key': '15s_test_kit_attachment_needed', 'label': 'If chlorine levels are monitored, attach label or spec sheet of test kit', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Section 16: Record Keeping System',
        'fields': [
            {'key': '16a_traceback_description', 'label': '16a. How records track products back and allow traceability', 'type': 'textarea'},
            {'key': '16b_lot_system', 'label': '16b. Lot and/or numbering system', 'type': 'textarea'},
            {'key': '16c_lot_number_packaging', 'label': '16c. How lot number is placed on packaging', 'type': 'textarea'},
            {'key': '16d_claim_identification', 'label': '16d. Do records identify the applicable organic claim?', 'type': 'yn'},
            {'key': '16e_organic_records', 'label': '16e. Which records do you keep for organic production?', 'type': 'textarea'},
            {'key': '16e_supporting_document_attachment_needed', 'label': 'You may submit a supporting document with a list', 'type': 'checkbox'},
            {'key': '16f_records_5years', 'label': '16f. Records maintained for a minimum of 5 years?', 'type': 'yn'},
            {'key': '16g_nonorganic_records', 'label': '16g. Which records do you keep for non-organic production?', 'type': 'checkbox_group'},
            {'key': '16g_nonorganic_records_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '16h_monitoring_practices', 'label': '16h. Monitoring practices and procedures', 'type': 'textarea'},
            {'key': '16i_monitoring_frequency', 'label': '16i. How/how frequently are they implemented?', 'type': 'textarea'},
            {'key': '16j_fraud_prevention_program', 'label': '16j. Organic fraud prevention program', 'type': 'textarea'},
            {'key': '16k_fraud_prevention_docs', 'label': '16k. Documents maintained for fraud prevention program', 'type': 'textarea'},
            {'key': '16l_fraud_prevention_monitoring', 'label': '16l. How do you monitor fraud prevention program effectiveness?', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 17: Trace back and Mass Balance',
        'fields': [
            {'key': None, 'label': None, 'type': 'static',
             'text': 'During the on-site inspection, inspectors are expected to conduct thorough trace-back and mass '
                     'balance audits to verify traceability and record-keeping requirements (§205.103). Please make sure '
                     'to have the documentation available needed to complete a mass balance and trace back during the '
                     'onsite audit.'},
        ],
    },
    {
        'title': 'Section 18: Affirmation',
        'fields': [
            {'key': None, 'label': None, 'type': 'static',
             'text': 'I affirm that all statements made in this application are true and correct. No prohibited '
                     'products have been applied to any of my organically managed fields during the three-year '
                     'period prior to projected harvest. I understand that the operation may be subject to '
                     'unannounced inspection and/or sampling for residues at any time as deemed appropriate to '
                     'ensure compliance with the Organic Foods Production Act of 1990 and National Organic Program '
                     'Rules and Regulations.'},
            {'key': '18_name', 'label': 'Name of Person completing this OSP', 'type': 'text'},
            {'key': '18_signature', 'label': 'Signature of Authorized Person', 'type': 'text'},
            {'key': '18_date', 'label': 'Date', 'type': 'date'},
        ],
    },
    {
        'title': 'Section 19: Field History Affidavit',
        'fields': [
            {'key': None, 'label': None, 'type': 'static',
             'text': 'Only for NEW fields added to certification request. Fill out this Field History Sheet for '
                     'every field that has not yet been certified.'},
            {'key': '19_farm_producer_name', 'label': 'Farm / Producer Name', 'type': 'text'},
            {'key': '19_field_id', 'label': 'Field name / ID number', 'type': 'text'},
            {'key': '19_transition_start_date', 'label': 'Transition Start Date', 'type': 'date'},
            {'key': '19_managed_3years', 'label': 'Have you managed this field for 3 or more years?', 'type': 'yn'},
            {'key': '19_statements_attached', 'label': 'If no, signed statements from previous manager attached?', 'type': 'yn'},
            {'key': '19_field_certified', 'label': 'Is this field currently certified?', 'type': 'yn'},
            {'key': '19_certification_attachment_needed', 'label': 'If yes, submit a copy of your certification', 'type': 'checkbox'},
            {'key': '19_last_substance_brand', 'label': 'Last prohibited substance applied — Brand/active ingredient', 'type': 'text'},
            {'key': '19_last_substance_date', 'label': 'Date of last application', 'type': 'date'},
            {'key': '19_history_json', 'label': 'Field History (per year)', 'type': 'table',
             'columns': [('year', 'Year'), ('crops', 'Crop(s)'), ('inputs_used', 'Inputs Used')]},
            {'key': '19_operator_name', 'label': 'Name of Operator', 'type': 'text'},
            {'key': '19_operator_date', 'label': 'Date', 'type': 'date'},
        ],
    },
    {
        'title': 'Section 20: Search Record – Commercial Availability of Seed and Planting Stock',
        'fields': [
            {'key': '20_search_record_json', 'label': 'Search Record', 'type': 'table',
             'columns': [('crop', 'Crop'), ('traits', 'Traits'), ('why_not_met', 'Why Not Met'),
                         ('suppliers_contacted', 'Suppliers Contacted'), ('date_contacted', 'Date Contacted'),
                         ('method_of_contact', 'Method of Contact')]},
        ],
    },
]
