# -*- coding: utf-8 -*-
"""
Definición de las 20 secciones del formulario "Cultivo" para el reporte
PDF — es el equivalente en español de CROP_REPORT_SECTIONS (mismas
keys/tipos/columnas de tabla, solo con labels en español) porque Cultivo
reutiliza literalmente los mismos JSON keys que Crop en su formulario web
(ver views/osp_form_cultivo.xml, que reutiliza los mismos ids de tabla
que Crop sin tocar TABLE_CONFIGS en osp_form.js).
"""

CULTIVO_REPORT_SECTIONS = [
    {
        'title': 'Sección 1: Información General',
        'fields': [
            {'key': '1_applicant_type', 'label': 'Seleccione una opción', 'type': 'text'},
            {'key': '1a_org_name', 'label': '1a. Nombre de la Organización', 'type': 'text'},
            {'key': '1b_dba_name', 'label': '1b. Nombre de la finca (si aplica)', 'type': 'text'},
            {'key': '1c_address', 'label': '1c. Dirección', 'type': 'text'},
            {'key': '1d_city', 'label': '1d. Ciudad', 'type': 'text'},
            {'key': '1e_state', 'label': '1e. Estado', 'type': 'm2o_state'},
            {'key': '1f_zip', 'label': '1f. Código Postal', 'type': 'text'},
            {'key': '1g_country', 'label': '1g. País', 'type': 'm2o_country'},
            {'key': '1h_same_as_billing', 'label': '1h. Información de Facturación: Igual que la dirección física', 'type': 'checkbox'},
            {'key': '1h_billing_address', 'label': 'Dirección de Facturación', 'type': 'text'},
            {'key': '1h_billing_city', 'label': 'Ciudad de Facturación', 'type': 'text'},
            {'key': '1h_billing_state', 'label': 'Estado de Facturación', 'type': 'text'},
            {'key': '1h_billing_zip', 'label': 'CP de Facturación', 'type': 'text'},
            {'key': '1h_billing_country', 'label': 'País de Facturación', 'type': 'text'},
            {'key': '1i_legal_rep_name', 'label': '1i. Representante Legal — Nombre', 'type': 'text'},
            {'key': '1i_legal_rep_email', 'label': 'Representante Legal — Correo', 'type': 'text'},
            {'key': '1i_legal_rep_phone', 'label': 'Representante Legal — Teléfono', 'type': 'text'},
            {'key': '1j_contacts_json', 'label': '1j. Representantes Autorizados', 'type': 'table',
             'columns': [('name', 'Nombre'), ('email', 'Correo'), ('phone', 'Teléfono')]},
            {'key': '1k_legal_status', 'label': '1k. Estatus Legal de Organización', 'type': 'text'},
            {'key': '1k_legal_status_other', 'label': 'Otra (especifique)', 'type': 'text'},
            {'key': '1l_state_registration', 'label': '1l. ¿Cuenta con un registro Estatal?', 'type': 'yn'},
            {'key': '1l_state_reg_number', 'label': 'Número de registro Estatal (si aplica)', 'type': 'text'},
            {'key': '1l_certificate_attachment_needed', 'label': 'Adjunte copia de su certificado Estatal más actual', 'type': 'checkbox'},
            {'key': '1m_nop_standards_copy', 'label': '1m. ¿Tiene una copia de los estándares orgánicos actuales de NOP?', 'type': 'yn'},
            {'key': '1n_description', 'label': '1n. Descripción de las actividades en su operación', 'type': 'textarea'},
            {'key': '1o_months_production', 'label': '1o. Meses de producción', 'type': 'text'},
            {'key': '1p_business_hours', 'label': '1p. Horarios laborales', 'type': 'text'},
            {'key': '1q_inspection_language', 'label': '1q. Idioma de inspección de preferencia', 'type': 'text'},
            {'key': '1r_documentation_language', 'label': '1r. Idioma de documentación', 'type': 'text'},
            {'key': '1s_operation_type', 'label': '1s. Tipo de operación', 'type': 'text'},
            {'key': '1t_produce_or_handle', 'label': '1t. ¿Su operación produce o maneja?', 'type': 'text'},
            {'key': '1u_directions', 'label': '1u. Indicaciones de ubicación / GPS', 'type': 'textarea'},
            {'key': '1u_available_contact', 'label': '¿En qué horario se encuentra disponible para contactar?', 'type': 'text'},
            {'key': '1u_available_inspection', 'label': '¿En qué horario se encuentra disponible para la inspección?', 'type': 'text'},
            {'key': '1v_income_5000_or_less', 'label': '1v. ¿Ingreso agrícola bruto proyectado ≤ $5,000/año?', 'type': 'yn'},
            {'key': '1v_resell_as_organic', 'label': 'Si sí, ¿venderá a quien revenda como "orgánico"?', 'type': 'yn'},
            {'key': '1w_is_renewal', 'label': '1w. ¿Es renovación? ¿Cambió algo desde la última certificación?', 'type': 'yn'},
            {'key': '1w_changes_summary', 'label': 'Si sí, resuma los cambios', 'type': 'textarea'},
            {'key': '1x_self_audit', 'label': '1x. ¿Ha realizado una autoauditoría orgánica?', 'type': 'yn'},
            {'key': '1x_self_audit_date', 'label': 'Si sí, indique la fecha', 'type': 'date'},
        ],
    },
    {
        'title': 'Sección 2: Certificación Orgánica Previa y/o No Conformidades',
        'fields': [
            {'key': '2_na', 'label': 'No aplica esta sección a mi operación', 'type': 'checkbox'},
            {'key': '2a_denied_certification', 'label': '2a. ¿Alguna vez se le ha negado, suspendido o revocado la certificación?', 'type': 'yn'},
            {'key': '2a_denied_certifier_name', 'label': 'Si sí, nombre del certificador', 'type': 'text'},
            {'key': '2a_documentation_attachment_needed', 'label': 'Envíe toda la documentación', 'type': 'checkbox'},
            {'key': '2b_certified_elsewhere', 'label': '2b. ¿Certificada actualmente con otra agencia?', 'type': 'yn'},
            {'key': '2b_certificate_attachment_needed', 'label': 'Adjunte copia del certificado actual', 'type': 'checkbox'},
            {'key': '2c_previously_certified', 'label': '2c. ¿Alguna vez se ha certificado en orgánico la operación?', 'type': 'yn_na'},
            {'key': '2c_certificate_attachment_needed', 'label': 'Adjunte copia del certificado orgánico anterior', 'type': 'checkbox'},
            {'key': '2d_noncompliances_na', 'label': 'N/A, sin incumplimientos', 'type': 'checkbox'},
            {'key': '2d_noncompliances_details', 'label': '2d. Incumplimientos de la última certificación y cómo se abordaron', 'type': 'textarea'},
            {'key': '2d_documentation_attachment_needed', 'label': 'Adjunte documentación de incumplimientos resueltos', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Sección 3: Mercados Internacionales',
        'fields': [
            {'key': '3_na', 'label': 'No aplica esta sección a mi operación', 'type': 'checkbox'},
            {'key': '3a_market_types', 'label': '3a. Seleccione la opción que aplica', 'type': 'checkbox_group'},
        ],
    },
    {
        'title': 'Sección 4: Cultivos y Campos',
        'fields': [
            {'key': '4a_producer_group', 'label': '4a. ¿Las áreas o sitios forman parte de un grupo de productores?', 'type': 'yn'},
            {'key': '4b_growers_list_attached', 'label': '4b. Lista de productores del grupo adjunta', 'type': 'yn'},
            {'key': '4c_other_agency_certified', 'label': '4c. ¿Sitios certificados por otra agencia?', 'type': 'yn'},
            {'key': '4c_previous_agency_name', 'label': 'Si sí, agencia de certificación', 'type': 'text'},
            {'key': '4d_noncompliances_open', 'label': '4d. ¿Incumplimiento menor abierto?', 'type': 'yn'},
            {'key': '4d_info_attached', 'label': 'Si sí, ¿información adjunta?', 'type': 'yn'},
            {'key': '4e_ics_list_attached', 'label': '4e. Lista de no cumplimientos del SIC adjunta', 'type': 'yn'},
            {'key': '4f_nonorganic_products', 'label': '4f. Productos no orgánicos y áreas donde se cultivan', 'type': 'textarea'},
            {'key': '4g_sites_json', 'label': '4g. Sitios de Producción', 'type': 'table',
             'columns': [('site_id', 'ID/Nombre'), ('site_address', 'Dirección'), ('city_state', 'Ciudad, Estado'),
                         ('zip', 'CP'), ('contact', 'Contacto'), ('description', 'Descripción')]},
            {'key': '4h_fields_json', 'label': '4h. Áreas/Terrenos', 'type': 'table',
             'columns': [('field_id', 'ID del Terreno'), ('parcel_address', 'Dirección/Descripción Legal'), ('area_type', 'Tipo de Área'),
                         ('units', 'Unidades'), ('rented_or_owned', 'Alquilado/Propio')]},
            {'key': '4i_same_field_ids', 'label': '4i. ¿Usa la misma identificación en su sistema de registros?', 'type': 'yn'},
            {'key': '4i_explain', 'label': 'Si no, explique', 'type': 'textarea'},
            {'key': '4j_crops_json', 'label': '4j. Cultivos', 'type': 'table',
             'columns': [('crop_requested', 'Cultivo Solicitado'), ('field_id', 'ID de Terreno'), ('total_planted_area', 'Área Total Sembrada'),
                         ('area_units', 'Unidades de Área'), ('projected_yield', 'Rendimiento Proyectado'), ('yield_units', 'Unidades de Rendimiento')]},
        ],
    },
    {
        'title': 'Sección 5: Productos',
        'fields': [
            {'key': '5a_marketing_types', 'label': '5a. Tipo de mercado', 'type': 'checkbox_group'},
            {'key': '5a_marketing_other', 'label': 'Especifique', 'type': 'text'},
            {'key': '5b_supply_chain_attached', 'label': '5b. Lista de cadena de suministro adjunta', 'type': 'yn'},
            {'key': '5c_list_all_id_marks', 'label': '5c. ¿Certificado debe listar todas las marcas?', 'type': 'yn'},
            {'key': '5d_products_json', 'label': '5d. Marcas de Identificación', 'type': 'table',
             'columns': [('product', 'Producto'), ('id_mark', 'Marca'), ('label_type', 'Tipo de Etiqueta'),
                         ('packing_with_id', '¿Empacará?'), ('organic_or_100', 'Orgánico/100%'), ('international_market', 'Mercados Internacionales')]},
        ],
    },
    {
        'title': 'Sección 6: Recursos Naturales y Biodiversidad',
        'fields': [
            {'key': '6a_soil_conservation', 'label': '6a. Prácticas de conservación del suelo', 'type': 'textarea'},
            {'key': '6b_erosion_problems', 'label': '6b. Problemas de erosión de suelo', 'type': 'textarea'},
            {'key': '6c_erosion_mitigation', 'label': '6c. Esfuerzos para reducir erosión / monitoreo', 'type': 'textarea'},
            {'key': '6d_natural_resources', 'label': '6d. Recursos naturales dentro/adyacentes a la operación', 'type': 'textarea'},
            {'key': '6e_woodland_na', 'label': 'N/A (zonas boscosas)', 'type': 'checkbox'},
            {'key': '6e_woodland_details', 'label': '6e. ¿Existen zonas boscosas o selváticas?', 'type': 'textarea'},
            {'key': '6f_wetlands_na', 'label': 'N/A (humedales)', 'type': 'checkbox'},
            {'key': '6f_wetlands_details', 'label': '6f. ¿Existen humedales?', 'type': 'textarea'},
            {'key': '6g_wildlife_na', 'label': 'N/A (fauna silvestre)', 'type': 'checkbox'},
            {'key': '6g_wildlife_details', 'label': '6g. ¿Existe fauna silvestre/biodiversidad?', 'type': 'textarea'},
            {'key': '6h_water_source', 'label': '6h. Fuente de agua', 'type': 'text'},
            {'key': '6i_water_use', 'label': '6i. Uso del agua en la operación', 'type': 'text'},
            {'key': '6j_irrigation_type', 'label': '6j. Sistema de riego utilizado', 'type': 'text'},
            {'key': '6k_water_cleaning', 'label': '6k. Limpieza de sistemas de riego / insumos utilizados', 'type': 'textarea'},
            {'key': '6l_shared_system', 'label': '6l. ¿Sistema de riego compartido con otro operador?', 'type': 'yn'},
            {'key': '6l_shared_products', 'label': 'Si sí, qué productos utilizan', 'type': 'text'},
            {'key': '6m_water_quality_practices', 'label': '6m. Prácticas para proteger calidad del agua', 'type': 'textarea'},
            {'key': '6n_water_testing', 'label': '6n. Programa de análisis de agua', 'type': 'textarea'},
            {'key': '6n_test_results_attachment_needed', 'label': 'Adjunte análisis de residuos y/o resultados de salinidad', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Sección 7: Requisitos del Terreno',
        'fields': [
            {'key': '7a_field_history_attached', 'label': '7a. Historial del terreno y documentos adjuntos', 'type': 'yn'},
            {'key': '7a_updated_map_attached', 'label': 'Mapas actualizados adjuntos', 'type': 'yn'},
            {'key': '7b_managed_3years', 'label': '7b. ¿Operación manejada por 3+ años?', 'type': 'yn'},
            {'key': '7b_statements_attachment_needed', 'label': 'Declaraciones firmadas del administrador anterior', 'type': 'checkbox'},
            {'key': '7c_evidence_no_prohibited', 'label': '7c. Evidencia de no uso de sustancias prohibidas (3 años previos)', 'type': 'textarea'},
            {'key': '7d_boundaries_defined', 'label': '7d. ¿Límites de terrenos definidos y reflejados en mapas?', 'type': 'yn'},
            {'key': '7e_acreage_consistent', 'label': '7e. ¿Área consistente entre mapas, historiales y este OSP?', 'type': 'yn'},
            {'key': '7f_buffer_zones', 'label': '7f. ¿Zonas de amortiguamiento establecidas?', 'type': 'text'},
            {'key': '7f_buffer_zones_explain', 'label': 'Explique / describa sus zonas de amortiguamiento', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 8: Semillas y Material de Propagación (Anual/Perenne)',
        'fields': [
            {'key': '8a_na', 'label': 'Esta sección no es aplicable a mi operación', 'type': 'checkbox'},
            {'key': '8a_seeds_json', 'label': '8a. Semillas', 'type': 'table',
             'columns': [('crop_variety', 'Cultivo/Variedad'), ('brand_supplier', 'Marca/Proveedor'), ('seed_type', 'Tipo'),
                         ('non_organic_treatment', 'Tratamiento (si no orgánica)'), ('non_gmo_documented', '¿No-OGM documentado?'),
                         ('seed_search_form_completed', '¿Formulario de búsqueda completado?')]},
            {'key': '8a_seeds_attachment_needed', 'label': 'Envíe documentos de soporte para las semillas', 'type': 'checkbox'},
            {'key': '8b_organic_seedlings', 'label': '8b. ¿Produce plántulas orgánicas en la finca?', 'type': 'yn_na'},
            {'key': '8c_seedling_procedures', 'label': '8c. Pasos y procedimientos llevados a cabo', 'type': 'textarea'},
            {'key': '8d_watering_equipment', 'label': '8d. Equipo del sistema de riego', 'type': 'textarea'},
            {'key': '8e_disease_prevention', 'label': '8e. Prevención de enfermedades/insectos en plántulas', 'type': 'textarea'},
            {'key': '8f_additional_services', 'label': '8f. ¿Servicios adicionales de propagación?', 'type': 'yn_na'},
            {'key': '8f_additional_services_describe', 'label': 'Si sí, describa', 'type': 'textarea'},
            {'key': '8g_na', 'label': 'Sección de material de propagación no aplicable', 'type': 'checkbox'},
            {'key': '8g_planting_stock_json', 'label': '8g. Material de propagación para perennes', 'type': 'table',
             'columns': [('type_crop_variety', 'Tipo (Cultivo-Variedad)'), ('source_supplier', 'Fuente/Proveedor'), ('seedling_type', 'Tipo'),
                         ('date_planted', 'Fecha de Plantación'), ('expected_harvest_date', 'Cosecha Esperada'), ('search_form_attached', '¿Formulario de búsqueda?')]},
        ],
    },
    {
        'title': 'Sección 9: Manejo de la Fertilidad de Suelo y Cultivo',
        'fields': [
            {'key': '9_general_na', 'label': 'Esta sección no es aplicable a mi operación', 'type': 'checkbox'},
            {'key': '9a_soil_types', 'label': '9a. Tipos de suelo en general', 'type': 'textarea'},
            {'key': '9b_soil_limitations', 'label': '9b. Limitaciones químicas/físicas/biológicas del suelo', 'type': 'textarea'},
            {'key': '9c_fertility_practices', 'label': '9c. Prácticas para mejorar/mantener fertilidad del suelo', 'type': 'textarea'},
            {'key': '9d_monitor_effectiveness', 'label': '9d. Monitoreo de efectividad del programa de fertilidad', 'type': 'textarea'},
            {'key': '9d_test_results_attachment_needed', 'label': 'Adjunte copias de resultados de pruebas disponibles', 'type': 'checkbox'},
            {'key': '9e_effectiveness_rating', 'label': '9e. Calificación de efectividad del programa de fertilidad', 'type': 'text'},
            {'key': '9e_anticipated_changes', 'label': 'Cambios anticipados', 'type': 'textarea'},
            {'key': '9_composting_na', 'label': 'Compostaje en la Finca no aplicable', 'type': 'checkbox'},
            {'key': '9f_compost_ingredients', 'label': '9f. Ingredientes/aditivos del compost y proporción', 'type': 'textarea'},
            {'key': '9g_composting_method', 'label': '9g. Método de compostaje', 'type': 'textarea'},
            {'key': '9h_cn_ratio', 'label': '9h. Proporción inicial de C:N', 'type': 'text'},
            {'key': '9i_compost_temp_maintained', 'label': '9i. ¿Temp. mantenida 131-170°F por 15+ días?', 'type': 'yn'},
            {'key': '9_manure_na', 'label': 'Uso de Estiércol no aplicable', 'type': 'checkbox'},
            {'key': '9j_manure_forms', 'label': '9j. Tipo de abono utilizado', 'type': 'checkbox_group'},
            {'key': '9j_manure_forms_other', 'label': 'Si es otro, especifique', 'type': 'text'},
            {'key': '9k_crop_types', 'label': '9k. Tipos de cultivos que siembra', 'type': 'checkbox_group'},
            {'key': '9k_documentation_attachment_needed', 'label': 'Documentación de soporte (estiércol crudo + consumo humano)', 'type': 'checkbox'},
            {'key': '9l_manure_source', 'label': '9l. Fuente del abono utilizado', 'type': 'text'},
            {'key': '9m_offfarm_manure_sources', 'label': '9m. Fuentes de estiércol fuera de la finca', 'type': 'textarea'},
            {'key': '9n_manure_ingredients', 'label': '9n. Ingredientes/aditivos del estiércol', 'type': 'textarea'},
            {'key': '9o_manure_contaminants', 'label': '9o. Contaminantes potenciales del estiércol', 'type': 'textarea'},
            {'key': '9o_analysis_attachment_needed', 'label': 'Adjunte análisis de residuos/especificaciones de aditivos', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Sección 10: Rotación de Cultivos',
        'fields': [
            {'key': '10_rotation_json', 'label': 'Planes de Rotación de Cultivos', 'type': 'table',
             'columns': [('rotation_plan', 'Plan de Rotación'), ('objectives', 'Objetivos')]},
        ],
    },
    {
        'title': 'Sección 11: Manejo de Plagas, Malezas y Enfermedades de Cultivos',
        'fields': [
            {'key': '11a_weed_disease_problems', 'label': '11a. Problemas con malezas/enfermedades y métodos de control', 'type': 'textarea'},
            {'key': '11b_restricted_strategy', 'label': '11b. Estrategia restringida utilizada', 'type': 'textarea'},
            {'key': '11c_mulch_removed', 'label': '11c. ¿Cobertura removida al final de la temporada?', 'type': 'yn_na'},
            {'key': '11c_mulch_not_removed_reason', 'label': 'Si no, por qué', 'type': 'textarea'},
            {'key': '11d_pest_problems', 'label': '11d. Problemas de plagas/enfermedades y estrategias preventivas', 'type': 'textarea'},
            {'key': '11e_practices_documented', 'label': '11e. ¿Prácticas preventivas documentadas?', 'type': 'yn'},
            {'key': '11f_insufficiency_documented', 'label': '11f. ¿Documenta insuficiencia antes de aplicar sustancia?', 'type': 'yn'},
            {'key': '11f_describe', 'label': 'Describa brevemente', 'type': 'textarea'},
            {'key': '11g_monitor_effectiveness', 'label': '11g. Monitoreo de efectividad del programa', 'type': 'textarea'},
            {'key': '11h_effectiveness_rating', 'label': '11h. Calificación de efectividad', 'type': 'text'},
            {'key': '11i_anticipated_changes', 'label': '11i. Cambios anticipados', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 12: Mantenimiento de la Integridad Orgánica – Insumos',
        'fields': [
            {'key': '12a_inputs_json', 'label': '12a. Insumos', 'type': 'table',
             'columns': [('input_used_for', 'Uso'), ('brand_name', 'Nombre del Producto'), ('ingredients', 'Ingredientes'),
                         ('compliance_approval_by', 'Aprobación de Conformidad Por'), ('label_compliance_docs_attached', '¿Docs Adjuntos?'),
                         ('restrictions_compliance_description', 'Cumplimiento Anotación NOP')]},
            {'key': '12b_storage_na', 'label': 'N/A (almacenamiento)', 'type': 'checkbox'},
            {'key': '12b_storage_description', 'label': '12b. Área de almacenamiento de insumos', 'type': 'textarea'},
            {'key': '12c_prevention_practices', 'label': '12c. Prácticas/barreras para prevenir mezcla/contaminación de insumos', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 13: Mantenimiento de la Integridad Orgánica – Áreas de Amortiguamiento y Producción Paralela',
        'fields': [
            {'key': '13_buffer_na', 'label': 'Áreas de Amortiguamiento no aplicable', 'type': 'checkbox'},
            {'key': '13a_risk_assessment', 'label': '13a. Frecuencia de evaluación de riesgo y riesgos actuales', 'type': 'textarea'},
            {'key': '13b_buffer_description', 'label': '13b. Principales áreas de amortiguamiento', 'type': 'textarea'},
            {'key': '13c_buffer_validated', 'label': '13c. ¿Validó que son suficientes?', 'type': 'yn'},
            {'key': '13d_buffer_sufficient_explain', 'label': '13d. Por qué son suficientes', 'type': 'textarea'},
            {'key': '13e_maps_updated', 'label': '13e. ¿Zonas mostradas/actualizadas en mapas?', 'type': 'yn'},
            {'key': '13f_buffer_harvest_use', 'label': '13f. Uso del cultivo cosechado de zonas de amortiguamiento', 'type': 'textarea'},
            {'key': '13g_buffer_harvest_safeguards', 'label': '13g. Salvaguardas durante cosecha en zonas de amortiguamiento', 'type': 'textarea'},
            {'key': '13h_safeguards', 'label': '13h. Medidas de seguridad adicionales', 'type': 'checkbox_group'},
            {'key': '13h_safeguards_other', 'label': 'Si es otra, especifique', 'type': 'text'},
            {'key': '13i_no_spray_signs', 'label': '13i. ¿Letreros "No Rociar" en caminos adyacentes?', 'type': 'yn'},
            {'key': '13j_fields_flood', 'label': '13j. ¿Campos se inundan frecuentemente?', 'type': 'yn'},
            {'key': '13j_flood_field_numbers', 'label': 'Si sí, números de terreno', 'type': 'text'},
            {'key': '13_split_na', 'label': 'Producción Paralela no aplicable', 'type': 'checkbox'},
            {'key': '13k_contamination_prevention', 'label': '13k. Prácticas/barreras para prevenir contaminación', 'type': 'textarea'},
            {'key': '13l_same_variety_mixed', 'label': '13l. ¿Cultiva la misma variedad orgánica/transición/no-orgánica?', 'type': 'yn'},
            {'key': '13l_commingling_prevention', 'label': 'Si sí, prácticas para prevenir mezcla', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 14: Mantenimiento de la Integridad Orgánica – Equipo y Cosecha',
        'fields': [
            {'key': '14_equipment_na', 'label': 'Equipo no aplicable', 'type': 'checkbox'},
            {'key': '14a_equipment_json', 'label': '14a. Equipo', 'type': 'table',
             'columns': [('equipment_name_model_code', 'Nombre/Modelo/Código'), ('owned_rented_custom', 'Propio/Alquilado/Compartido'),
                         ('used_for', 'Cultivo para el que se Utiliza'), ('cleaning_method', 'Método de Limpieza')]},
            {'key': '14_harvest_na', 'label': 'Cosecha no aplicable', 'type': 'checkbox'},
            {'key': '14b_harvest_method', 'label': '14b. ¿Cómo se cosechan sus cultivos orgánicos?', 'type': 'checkbox_group'},
            {'key': '14b_harvest_description', 'label': 'Descripción breve', 'type': 'textarea'},
            {'key': '14c_subcontract_harvest', 'label': '14c. ¿Subcontrata mano de obra de cosecha?', 'type': 'yn'},
            {'key': '14c_subcontractor_info', 'label': 'Si sí, nombre y dirección del contratista', 'type': 'text'},
            {'key': '14d_subcontractor_training', 'label': '14d. Capacitación de mano de obra subcontratada', 'type': 'textarea'},
            {'key': '14e_containers_used', 'label': '14e. Contenedores usados para cosecha', 'type': 'text'},
            {'key': '14f_containers_condition', 'label': '14f. ¿Contenedores nuevos o usados?', 'type': 'text'},
            {'key': '14f_previous_contents', 'label': 'Si usados, qué contenían antes', 'type': 'text'},
            {'key': '14g_containers_organic_only', 'label': '14g. ¿Contenedores exclusivos para orgánico?', 'type': 'yn'},
            {'key': '14h_contamination_problems', 'label': '14h. Problemas de contaminación/mezcla en cosecha', 'type': 'textarea'},
            {'key': '14i_protection_steps', 'label': '14i. Pasos para proteger de mezcla/contaminación', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 15: Manejo Post-Cosecha, Almacenamiento y Transporte',
        'fields': [
            {'key': '15_handling_na', 'label': 'Manipulación Post-Cosecha no aplicable', 'type': 'checkbox'},
            {'key': '15a_handling_procedures', 'label': '15a. Procedimientos y equipo de manejo post-cosecha', 'type': 'textarea'},
            {'key': '15a_diagrams_attachment_needed', 'label': 'Adjunte diagrama de flujo y plano de planta', 'type': 'checkbox'},
            {'key': '15b_shared_handling', 'label': '15b. ¿Área/equipo compartido orgánico y no-orgánico?', 'type': 'yn'},
            {'key': '15b_prevention_steps', 'label': 'Si sí, medidas para prevenir mezcla', 'type': 'textarea'},
            {'key': '15c_shipping_form', 'label': '15c. Forma de envío de productos terminados', 'type': 'text'},
            {'key': '15d_packaging_materials', 'label': '15d. Tipos de material de empaque', 'type': 'text'},
            {'key': '15e_packaging_documentation', 'label': '15e. Documentación de empaque libre de fungicida/fumigante', 'type': 'textarea'},
            {'key': '15e_evidence_attachment_needed', 'label': 'Adjunte evidencia documental', 'type': 'checkbox'},
            {'key': '15f_water_used', 'label': '15f. ¿Usa agua en manejo post-cosecha?', 'type': 'yn_na'},
            {'key': '15g_water_direct_contact', 'label': '15g. ¿Contacto directo con cultivo/superficies alimentarias?', 'type': 'yn'},
            {'key': '15h_water_documented', 'label': '15h. ¿Documentó cumplimiento de Ley de Agua Potable?', 'type': 'yn'},
            {'key': '15_storage_na', 'label': 'Almacenamiento no aplicable', 'type': 'checkbox'},
            {'key': '15i_storage_id', 'label': 'Identificación del área de almacenamiento', 'type': 'text'},
            {'key': '15i_storage_crop_type', 'label': 'Tipo de cultivo', 'type': 'text'},
            {'key': '15i_storage_type', 'label': 'Tipo de almacenamiento', 'type': 'text'},
            {'key': '15i_storage_capacity', 'label': 'Capacidad', 'type': 'text'},
            {'key': '15i_storage_used_for', 'label': 'Utilizado para', 'type': 'text'},
            {'key': '15j_shared_storage', 'label': '15j. ¿Mismas áreas para orgánico/transición/amortiguamiento/convencional?', 'type': 'yn'},
            {'key': '15j_segregation_method', 'label': 'Si sí, cómo segrega', 'type': 'textarea'},
            {'key': '15k_storage_cleaning', 'label': '15k. Limpieza de unidades antes de almacenar', 'type': 'textarea'},
            {'key': '15l_pest_control_storage', 'label': '15l. Prevención/control de plagas en almacenamiento', 'type': 'textarea'},
            {'key': '15m_offsite_storage', 'label': '15m. ¿Productos almacenados fuera de sitio?', 'type': 'yn'},
            {'key': '15_transport_na', 'label': 'Transporte no aplicable', 'type': 'checkbox'},
            {'key': '15n_transport_responsible', 'label': '15n. Responsable del transporte', 'type': 'text'},
            {'key': '15n_transport_responsible_other', 'label': 'Si es otro, especifique', 'type': 'text'},
            {'key': '15o_transport_method', 'label': '15o. Cómo se transportan los productos orgánicos', 'type': 'textarea'},
            {'key': '15p_transport_contamination_problems', 'label': '15p. Riesgos de contaminación en transporte', 'type': 'textarea'},
            {'key': '15q_transport_protection_steps', 'label': '15q. Medidas para proteger integridad en transporte', 'type': 'checkbox_group'},
            {'key': '15q_transport_protection_other', 'label': 'Si es otro, especifique', 'type': 'text'},
            {'key': '15_chlorine_na', 'label': 'Uso de Cloro no aplicable', 'type': 'checkbox'},
            {'key': '15r_use_chlorine', 'label': '15r. ¿Usa cloro o productos con cloro?', 'type': 'yn'},
            {'key': '15r_chlorine_details', 'label': 'Si sí, propósito/formulación/dónde/cómo se usa', 'type': 'textarea'},
            {'key': '15r_label_attachment_needed', 'label': 'Adjunte etiqueta', 'type': 'checkbox'},
            {'key': '15s_chlorine_verification', 'label': '15s. Verificación/documentación de cumplimiento NOP de cloro', 'type': 'textarea'},
            {'key': '15s_test_kit_attachment_needed', 'label': 'Si se monitorea, adjunte etiqueta o ficha del kit', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Sección 16: Sistema de Mantenimiento de Registros',
        'fields': [
            {'key': '16a_traceback_description', 'label': '16a. Cómo los registros rastrean los productos', 'type': 'textarea'},
            {'key': '16b_lot_system', 'label': '16b. Sistema de lote/numeración', 'type': 'textarea'},
            {'key': '16c_lot_number_packaging', 'label': '16c. Cómo asegura número de lote en el envase', 'type': 'textarea'},
            {'key': '16d_claim_identification', 'label': '16d. ¿Registros identifican declaración aplicable?', 'type': 'yn'},
            {'key': '16e_organic_records', 'label': '16e. Registros para producción orgánica', 'type': 'textarea'},
            {'key': '16e_supporting_document_attachment_needed', 'label': 'Puede adjuntar una lista de registros', 'type': 'checkbox'},
            {'key': '16f_records_5years', 'label': '16f. ¿Registros mantenidos 5+ años?', 'type': 'yn'},
            {'key': '16g_nonorganic_records', 'label': '16g. Registros para producción no-orgánica', 'type': 'checkbox_group'},
            {'key': '16g_nonorganic_records_other', 'label': 'Si es otro, especifique', 'type': 'text'},
            {'key': '16h_monitoring_practices', 'label': '16h. Prácticas y procedimientos de monitoreo', 'type': 'textarea'},
            {'key': '16i_monitoring_frequency', 'label': '16i. Cómo/frecuencia de implementación', 'type': 'textarea'},
            {'key': '16j_fraud_prevention_program', 'label': '16j. Programa de prevención de fraude orgánico', 'type': 'textarea'},
            {'key': '16k_fraud_prevention_docs', 'label': '16k. Documentos de prevención de fraude', 'type': 'textarea'},
            {'key': '16l_fraud_prevention_monitoring', 'label': '16l. Monitoreo de efectividad anti-fraude', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Sección 17: Balance de Masas y Trazabilidad',
        'fields': [
            {'type': 'static', 'text': 'Sin campos — sección informativa que explica las auditorías de trazabilidad y balance de masas realizadas durante la inspección in situ.'},
        ],
    },
    {
        'title': 'Sección 18: Afirmación',
        'fields': [
            {'type': 'static', 'text': 'Yo afirmo que todas las declaraciones hechas en esta aplicación son verdaderas y correctas. Firma electrónica es aceptada.'},
            {'key': '18_name', 'label': 'Nombre', 'type': 'text'},
            {'key': '18_signature', 'label': 'Firma', 'type': 'text'},
            {'key': '18_date', 'label': 'Fecha', 'type': 'date'},
        ],
    },
    {
        'title': 'Sección 19: Historial de Campo - Declaración Jurada',
        'fields': [
            {'type': 'static', 'text': 'Solo para campos NUEVOS agregados a la solicitud de certificación. Complete esta hoja para cada campo que aún no ha sido certificado.'},
            {'key': '19_farm_producer_name', 'label': 'Nombre de la Finca/Productor', 'type': 'text'},
            {'key': '19_field_id', 'label': 'Nombre del campo/ID número', 'type': 'text'},
            {'key': '19_transition_start_date', 'label': 'Fecha de inicio de transición', 'type': 'date'},
            {'key': '19_managed_3years', 'label': '¿Ha administrado el campo por más de 3 años?', 'type': 'yn'},
            {'key': '19_statements_attached', 'label': 'Si no, declaraciones firmadas del administrador anterior adjuntas', 'type': 'yn'},
            {'key': '19_field_certified', 'label': '¿Está el área certificada actualmente?', 'type': 'yn'},
            {'key': '19_certification_attachment_needed', 'label': 'Si sí, adjunte copia del certificado actual', 'type': 'checkbox'},
            {'key': '19_last_substance_brand', 'label': 'Última sustancia prohibida aplicada — Marca/ingrediente activo', 'type': 'text'},
            {'key': '19_last_substance_date', 'label': 'Fecha de la última aplicación', 'type': 'date'},
            {'key': '19_history_json', 'label': 'Historial de Campo (por año)', 'type': 'table',
             'columns': [('year', 'Año'), ('crops', 'Cultivo(s)'), ('inputs_used', 'Insumos Aplicados')]},
            {'key': '19_operator_name', 'label': 'Nombre del Representante Legal', 'type': 'text'},
            {'key': '19_operator_date', 'label': 'Fecha', 'type': 'date'},
        ],
    },
    {
        'title': 'Sección 20: Registro de Búsqueda – Disponibilidad Comercial de Semillas y Material de Siembra',
        'fields': [
            {'key': '20_search_record_json', 'label': 'Registro de Búsqueda', 'type': 'table',
             'columns': [('crop', 'Cultivo'), ('traits', 'Características'), ('why_not_met', 'Por Qué No Cumple'),
                         ('suppliers_contacted', 'Proveedores Contactados'), ('date_contacted', 'Fecha de Contacto'),
                         ('method_of_contact', 'Método de Contacto')]},
        ],
    },
]
