# -*- coding: utf-8 -*-
"""
Definición de las 15 secciones del formulario "Handler" para el reporte
PDF — mismo formato/tipos que CROP_REPORT_SECTIONS (ver
osp_crop_report_data.py para la lista de tipos soportados). Es la ÚNICA
fuente de verdad de qué preguntas existen y de qué tipo son, sacada
directamente de FORM_SPEC_HANDLER.md y verificada contra los `name`
reales de views/osp_form_handler.xml.

Tipo adicional usado aquí (no existe en Crop): `fixed_rows` — para la
Sección 7b (Storage), que en el formulario web es un número FIJO de 4
categorías (Ingredients/Finished Goods/Packaging Materials/Other), no una
tabla dinámica de agregar/quitar filas. Ver _report_fixed_rows en
osp_report_common.py.
"""

HANDLER_REPORT_SECTIONS = [
    {
        'title': 'Section 1: General Information',
        'fields': [
            {'key': '1_applicant_type', 'label': 'Choose one', 'type': 'text'},
            {'key': '1a_org_name', 'label': '1a. Organization Name', 'type': 'text'},
            {'key': '1b_dba_name', 'label': '1b. dba Name (if applicable)', 'type': 'text'},
            {'key': '1c_address', 'label': '1c. Address', 'type': 'text'},
            {'key': '1d_city', 'label': '1d. City', 'type': 'text'},
            {'key': '1e_state', 'label': '1e. State', 'type': 'm2o_state'},
            {'key': '1f_zip', 'label': '1f. Zip code', 'type': 'text'},
            {'key': '1g_country', 'label': '1g. Country', 'type': 'm2o_country'},
            {'key': '1h_same_as_billing', 'label': '1h. Billing information: Same as Physical address', 'type': 'checkbox'},
            {'key': '1h_billing_address', 'label': 'Billing Address', 'type': 'text'},
            {'key': '1h_billing_city', 'label': 'Billing City', 'type': 'text'},
            {'key': '1h_billing_state', 'label': 'Billing State', 'type': 'text'},
            {'key': '1h_billing_zip', 'label': 'Billing Zip', 'type': 'text'},
            {'key': '1h_billing_country', 'label': 'Billing Country', 'type': 'text'},
            {'key': '1i_legal_rep_name', 'label': '1i. Legal Representative — Name', 'type': 'text'},
            {'key': '1i_legal_rep_email', 'label': 'Legal Representative — Email', 'type': 'text'},
            {'key': '1i_legal_rep_phone', 'label': 'Legal Representative — Phone', 'type': 'text'},
            {'key': '1j_contacts_json', 'label': '1j. Authorized Contacts', 'type': 'table',
             'columns': [('name', 'Name'), ('email', 'Email'), ('phone', 'Phone')]},
            {'key': '1k_legal_status', 'label': '1k. Organization Legal status', 'type': 'text'},
            {'key': '1k_legal_status_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '1l_state_registration', 'label': '1l. Do you obtain a State registration?', 'type': 'yn'},
            {'key': '1l_state_reg_number', 'label': 'State registration # (if applicable)', 'type': 'text'},
            {'key': '1l_certificate_attachment_needed', 'label': 'Attach a copy of your current State certificate', 'type': 'checkbox'},
            {'key': '1m_nop_standards_copy', 'label': '1m. Do you have a copy of current NOP organic standards?', 'type': 'yn'},
            {'key': '1n_description', 'label': "1n. Description of operation's activities", 'type': 'textarea'},
            {'key': '1o_months_production', 'label': '1o. Months of Production', 'type': 'text'},
            {'key': '1p_business_hours', 'label': '1p. Business hours', 'type': 'text'},
            {'key': '1q_inspection_language', 'label': '1q. Inspection language preference', 'type': 'text'},
            {'key': '1r_documentation_language', 'label': '1r. What language is your documentation?', 'type': 'text'},
            {'key': '1s_produce_or_handle', 'label': '1s. What does your operation produce or handle', 'type': 'text'},
            {'key': '1t_directions', 'label': '1t. Driving directions / GPS confirmation', 'type': 'textarea'},
            {'key': '1t_available_contact', 'label': 'When are you available to contact?', 'type': 'text'},
            {'key': '1t_available_inspection', 'label': 'When are you available for inspection?', 'type': 'text'},
            {'key': '1u_income_5000_or_less', 'label': "1u. Operation's projected gross agricultural income from organic sales ≤ $5,000/year?", 'type': 'yn'},
            {'key': '1u_resell_as_organic', 'label': 'If yes, do you intend to sell to anyone reselling as "organic"?', 'type': 'yn'},
            {'key': '1v_is_renewal', 'label': '1v. Is this a renewal? Has anything changed since your last certification?', 'type': 'yn'},
            {'key': '1v_changes_summary', 'label': 'If yes, summarize the changes', 'type': 'textarea'},
            {'key': '1w_self_audit', 'label': '1w. Have you conducted an organic self-audit?', 'type': 'yn'},
            {'key': '1w_self_audit_date', 'label': 'If yes, indicate the date', 'type': 'date'},
        ],
    },
    {
        'title': 'Section 2: Prior Organic Certification and/or Noncompliance',
        'fields': [
            {'key': '2_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '2a_denied_certification', 'label': '2a. Has this organization ever been denied certification, suspended or revoked?', 'type': 'yn'},
            {'key': '2a_certifier_and_docs', 'label': 'If yes, certifier name and documentation', 'type': 'textarea'},
            {'key': '2a_documentation_attachment_needed', 'label': 'Provide all documentation', 'type': 'checkbox'},
            {'key': '2b_certified_elsewhere', 'label': '2b. Is this organization currently certified organic with another agency?', 'type': 'yn'},
            {'key': '2b_certificate_attachment_needed', 'label': 'Attach a copy of your current organic certificate', 'type': 'checkbox'},
            {'key': '2c_previously_certified', 'label': '2c. For first time auditees, has this organization ever been certified organic?', 'type': 'yn_na'},
            {'key': '2c_certificate_attachment_needed', 'label': 'Attach a copy of your previous organic certificate', 'type': 'checkbox'},
            {'key': '2d_noncompliances_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '2d_noncompliances_details', 'label': '2d. Non-compliances from last certification and how addressed', 'type': 'textarea'},
            {'key': '2d_documentation_attachment_needed', 'label': 'Attach documentation that verified non-compliances have been addressed', 'type': 'checkbox'},
        ],
    },
    {
        'title': 'Section 3: International Markets',
        'fields': [
            {'key': '3_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '3a_market_types', 'label': '3a. Select all that applies', 'type': 'checkbox_group'},
        ],
    },
    {
        'title': 'Section 4: Facility Information & Products',
        'fields': [
            {'key': '4a_operation_types', 'label': '4a. Type of operation (select all that apply)', 'type': 'checkbox_group'},
            {'key': '4a_operation_types_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '4b_other_sites', 'label': '4b. Do you manage other sites other than the site address in section 1?', 'type': 'yn'},
            {'key': '4b_sites_json', 'label': 'Sites', 'type': 'table',
             'columns': [('site_id', 'Site ID/Name'), ('site_address', 'Site Address'), ('city_state', 'City, State'),
                         ('zip_code', 'Zip'), ('contact', 'Contact'), ('description', 'Description')]},
            {'key': '4c_flow_diagram_attached', 'label': '4c. Operation Flow Diagram Attached', 'type': 'yn'},
            {'key': '4d_nonorganic_products_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '4d_nonorganic_products', 'label': '4d. Non-organic products handled in facility', 'type': 'textarea'},
            {'key': '4e_pct_nonorganic', 'label': '4e. Projected % of total production — Non-organic', 'type': 'text'},
            {'key': '4e_pct_organic', 'label': 'Projected % of total production — Organic', 'type': 'text'},
            {'key': '4f_other_certifications', 'label': '4f. Does your operation have any certifications besides Organic?', 'type': 'yn'},
            {'key': '4f_other_certifications_details', 'label': 'If yes, auditing company and scheme(s)', 'type': 'text'},
            {'key': '4g_uses_ingredients', 'label': '4g. Do you utilize and/or add ingredients for processing products?', 'type': 'yn'},
            {'key': '4g_ingredients_list_attachment_needed', 'label': 'Submit a list of the ingredients used', 'type': 'checkbox'},
            {'key': '4h_contamination_prevention_na', 'label': 'N/A', 'type': 'checkbox'},
            {'key': '4h_contamination_prevention', 'label': '4h. How you prevent contamination/commingling between organic and non-organic', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 5: Products – To Be Listed on Certificate by ID Mark & Market',
        'fields': [
            {'key': '5a_marketing_types', 'label': '5a. Type of Marketing — select all that apply', 'type': 'checkbox_group'},
            {'key': '5a_marketing_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '5b_supply_chain_attached', 'label': '5b. Master Supply Chain and Product List attached', 'type': 'yn'},
            {'key': '5c_list_all_id_marks', 'label': '5c. Do you require your organic certificate to list all ID Marks?', 'type': 'yn'},
            {'key': '5d_products_json', 'label': '5d. Products', 'type': 'table',
             'columns': [('product', 'Product'), ('id_mark', 'ID Mark'), ('label_type', 'Label Type'),
                         ('packing_with_id', 'Packing w/ ID Mark?'), ('organic_or_100', 'Organic/100% Organic?'),
                         ('international_market', 'International Market')]},
        ],
    },
    {
        'title': 'Section 6: Biodiversity & Natural Resources',
        'fields': [
            {'key': '6a_biodiversity_program', 'label': '6a. Biodiversity program', 'type': 'textarea'},
            {'key': '6b_natural_resources', 'label': '6b. Natural resources within/surrounding the operation', 'type': 'textarea'},
            {'key': '6_water_use_na', 'label': 'Water Use — N/A', 'type': 'checkbox'},
            {'key': '6c_water_source', 'label': '6c. Water source', 'type': 'text'},
            {'key': '6d_water_analysis_attached', 'label': '6d. Water analysis attached (non-municipal source)', 'type': 'yn'},
            {'key': '6d_water_analysis_doc_name', 'label': 'Name of document', 'type': 'text'},
            {'key': '6e_water_conservation', 'label': '6e. Water conservation practices', 'type': 'textarea'},
            {'key': '6f_water_use_capacity', 'label': '6f. Water use capacity', 'type': 'text'},
            {'key': '6g_onsite_water_treatments', 'label': '6g. Onsite water treatments used?', 'type': 'yn'},
            {'key': '6_boiler_na', 'label': 'Boiler Use — N/A', 'type': 'checkbox'},
            {'key': '6h_steam_contact', 'label': '6h. Steam direct contact with organic products?', 'type': 'yn'},
            {'key': '6h_boiler_chemicals_used', 'label': 'Do you use boiler chemicals?', 'type': 'yn'},
            {'key': '6h_boiler_chemicals_attached', 'label': 'Boiler chemicals list on Materials List attached?', 'type': 'yn'},
            {'key': '6h_contamination_prevention', 'label': 'How you prevent contamination from boiler chemicals', 'type': 'textarea'},
            {'key': '6i_boiler_condensation_tested', 'label': '6i. Is the boiler condensation tested?', 'type': 'yn'},
            {'key': '6i_results_attachment_needed', 'label': 'Attach the results from the analysis', 'type': 'checkbox'},
            {'key': '6j_waste_management', 'label': '6j. Waste management practices', 'type': 'textarea'},
            {'key': '6k_recycle_waste', 'label': '6k. Do you recycle waste materials?', 'type': 'yn'},
            {'key': '6k_recycle_describe', 'label': 'Describe', 'type': 'textarea'},
            {'key': '6l_energy_conservation', 'label': '6l. Energy conservation practices', 'type': 'textarea'},
            {'key': '6m_air_quality', 'label': '6m. Air quality management practices', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 7: Maintenance of Organic Integrity – Storage & Post Harvest Handling',
        'fields': [
            {'key': '7a_storage_areas', 'label': '7a. Areas utilized for storage', 'type': 'textarea'},
            {
                'label': '7b. Storage', 'type': 'fixed_rows', 'prefix': '7b', 'row_header': 'Category',
                'columns': [('id_name', 'ID Name/Number'), ('type', 'Type'), ('dedicated_organic', 'Dedicated Organic'),
                            ('offsite_used', 'Offsite Used'), ('capacity', 'Capacity')],
                'rows': [
                    {'key': 'ingredients', 'label': 'Ingredients'},
                    {'key': 'finished_goods', 'label': 'Finished Goods'},
                    {'key': 'packaging_materials', 'label': 'Packaging Materials'},
                    {'key': 'other', 'label_key': '7b_other_label'},
                ],
            },
            {'key': '7c_shipping_form', 'label': '7c. Form in which finished products are shipped', 'type': 'text'},
            {'key': '7d_packaging_material_type', 'label': '7d. Type of packaging material used', 'type': 'text'},
            {'key': '7e_packaging_free_of_synthetics', 'label': '7e. Packaging free of synthetic fungicide/preservative/fumigant?', 'type': 'yn_na'},
            {'key': '7e_explain', 'label': 'If no, explain', 'type': 'textarea'},
            {'key': '7e_evidence_attachment_needed', 'label': 'Attach documented evidence', 'type': 'checkbox'},
            {'key': '7f_water_used_postharvest', 'label': '7f. Water used in post-harvest handling?', 'type': 'yn'},
            {'key': '7f_direct_contact', 'label': 'Direct contact with crop or food contact surfaces?', 'type': 'yn'},
            {'key': '7f_water_documented', 'label': 'Documented water meets Safe Drinking Water Act?', 'type': 'yn'},
            {'key': '7f_test_results_attachment_needed', 'label': 'Attach test results', 'type': 'checkbox'},
            {'key': '7g_offsite_storage', 'label': '7g. Organic ingredients/finished goods ever stored offsite?', 'type': 'yn'},
        ],
    },
    {
        'title': 'Section 8: Maintenance of Organic Integrity - Equipment and Sanitation',
        'fields': [
            {'key': '8a_equipment_list', 'label': '8a. Equipment types used in operation', 'type': 'textarea'},
            {'key': '8b_equipment_dedicated_organic', 'label': '8b. Is all equipment dedicated Organic?', 'type': 'yn'},
            {'key': '8b_prevention_practices', 'label': 'If no, practices/barriers to prevent mixing/contamination', 'type': 'textarea'},
            {'key': '8c_equipment_cleaned', 'label': '8c. Equipment cleaned/purged prior to organic handling?', 'type': 'yn_na'},
            {'key': '8d_cleaning_procedures', 'label': '8d. Equipment cleaning procedures', 'type': 'textarea'},
            {'key': '8e_personnel_measures', 'label': '8e. Measures to protect organic integrity', 'type': 'textarea'},
            {'key': '8f_sanitation_program', 'label': '8f. Sanitation program', 'type': 'textarea'},
            {'key': '8_chlorine_na', 'label': 'Use of Chlorine — N/A', 'type': 'checkbox'},
            {'key': '8g_use_chlorine', 'label': '8g. Do you use chlorine or chlorine containing products?', 'type': 'yn'},
            {'key': '8h_chlorine_details', 'label': '8h. Purpose/formulation/where/how used', 'type': 'textarea'},
            {'key': '8i_chlorine_verification', 'label': '8i. How you verify/document chlorine use meets NOP requirements', 'type': 'textarea'},
            {'key': '8j_commodities_sampled', 'label': '8j. Are organic commodities sampled?', 'type': 'yn'},
            {'key': '8j_tools_dedicated', 'label': 'Are sampling tools dedicated for organic use only?', 'type': 'yn'},
            {'key': '8j_cleaning_description', 'label': 'If no, how sampling equipment is cleaned', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 9: Maintenance of Organic Integrity – Inputs',
        'fields': [
            {'key': '9a_inputs_json', 'label': '9a. Inputs', 'type': 'table',
             'columns': [('input_used_for', 'Used for'), ('brand_name', 'Brand Name'), ('ingredients', 'Ingredients'),
                         ('food_contact', 'Food Contact?'), ('compliance_approval_by', 'Compliance Approval By'),
                         ('label_docs_attached', 'Label/Docs Attached'), ('restrictions_description', 'Restrictions')]},
        ],
    },
    {
        'title': 'Section 10: Maintenance of Organic Integrity – Transportation',
        'fields': [
            {'key': '10a_responsible_for_transport', 'label': '10a. Responsible for transportation of incoming/outgoing goods?', 'type': 'yn'},
            {'key': '10b_receiving_method', 'label': '10b. How organic products are received', 'type': 'text'},
            {'key': '10c_shipping_method', 'label': '10c. How organic products are shipped', 'type': 'text'},
            {'key': '10d_unsealed_or_reusable', 'label': '10d. Receive in permeable/unsealed packaging or re-usable containers?', 'type': 'yn'},
            {'key': '10d_verification_methods', 'label': 'How you verify not contaminated during transportation', 'type': 'checkbox_group'},
            {'key': '10d_verification_methods_other', 'label': 'If other, specify', 'type': 'text'},
        ],
    },
    {
        'title': 'Section 11: Maintenance of Organic Integrity – Packaging',
        'fields': [
            {'key': '11_na', 'label': 'This section is not applicable to my operation', 'type': 'checkbox'},
            {'key': '11a_packaging_type', 'label': '11a. Type of packaging used', 'type': 'text'},
            {'key': '11b_food_grade', 'label': '11b. Is all packaging food grade?', 'type': 'yn'},
            {'key': '11c_reused', 'label': '11c. Are packaging materials/containers ever re-used?', 'type': 'yn'},
            {'key': '11c_previous_use', 'label': 'If yes, previous use', 'type': 'textarea'},
            {'key': '11c_cleaning_procedure', 'label': 'Cleaning procedure prior to reuse', 'type': 'textarea'},
            {'key': '11d_free_of_synthetics', 'label': '11d. Packaging free from synthetic fungicides/preservatives/fumigants?', 'type': 'yn'},
            {'key': '11d_verification', 'label': 'How this is verified', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 12: Maintenance of Organic Integrity – Pest Management',
        'fields': [
            {'key': '12a_pest_control_responsible', 'label': '12a. Who is responsible for pest control?', 'type': 'text'},
            {'key': '12a_contractor_info', 'label': 'Contractor name & number', 'type': 'text'},
            {'key': '12b_pest_issues', 'label': '12b. Do you have any pest issues?', 'type': 'yn'},
            {'key': '12b_problem_pests', 'label': 'If yes, problem pests', 'type': 'textarea'},
            {'key': '12c_pest_controls', 'label': '12c. Pest controls in place', 'type': 'checkbox_group'},
            {'key': '12c_pest_controls_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '12d_prevention_strategies', 'label': '12d. Strategies to prevent damage before applying approved substance', 'type': 'textarea'},
            {'key': '12e_practices_documented', 'label': '12e. Are preventative practices documented?', 'type': 'yn'},
            {'key': '12f_sufficiency_documented', 'label': '12f. Do you document if preventative practices were sufficient?', 'type': 'yn'},
            {'key': '12g_materials_in_processing_areas', 'label': '12g. Pest control materials used in processing/storage areas?', 'type': 'yn'},
            {'key': '12g_contamination_prevention', 'label': 'If yes, procedures to prevent contamination', 'type': 'textarea'},
            {'key': '12h_unlisted_materials_used', 'label': '12h. Materials not listed on §205.605/606 used?', 'type': 'yn'},
            {'key': '12h_justification_documented', 'label': 'Documented justification & hierarchy verification?', 'type': 'yn'},
            {'key': '12i_practices_documented_records', 'label': '12i. Pest control practices/material use documented?', 'type': 'yn'},
            {'key': '12i_records_used', 'label': 'If yes, records used', 'type': 'checkbox_group'},
            {'key': '12j_monitor_effectiveness', 'label': '12j. How you monitor effectiveness of pest management program', 'type': 'textarea'},
            {'key': '12k_effectiveness_rating', 'label': '12k. Effectiveness rating', 'type': 'text'},
            {'key': '12l_anticipated_changes', 'label': '12l. Anticipated changes', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 13: Record-Keeping System',
        'fields': [
            {'key': '13a_traceback_description', 'label': '13a. How records track products (traceback)', 'type': 'textarea'},
            {'key': '13b_lot_system', 'label': '13b. Lot/numbering system', 'type': 'textarea'},
            {'key': '13c_lot_number_packaging', 'label': '13c. How lot number is placed on packaging', 'type': 'textarea'},
            {'key': '13d_claim_identification', 'label': '13d. Records identify applicable claim (100% organic, etc.)?', 'type': 'yn'},
            {'key': '13d_claim_identification_details', 'label': 'Details', 'type': 'textarea'},
            {'key': '13e_organic_records', 'label': '13e. Records kept for organic production', 'type': 'textarea'},
            {'key': '13f_records_5years', 'label': '13f. Records maintained for 5+ years?', 'type': 'yn'},
            {'key': '13g_nonorganic_records', 'label': '13g. Records kept for non-organic production', 'type': 'checkbox_group'},
            {'key': '13g_nonorganic_records_other', 'label': 'If other, specify', 'type': 'text'},
            {'key': '13h_monitoring_practices', 'label': '13h. Monitoring practices/procedures', 'type': 'textarea'},
            {'key': '13i_monitoring_frequency', 'label': '13i. How/how frequently monitoring is implemented', 'type': 'textarea'},
            {'key': '13j_fraud_prevention_program', 'label': '13j. Organic fraud prevention program', 'type': 'textarea'},
            {'key': '13k_fraud_prevention_docs', 'label': '13k. Documents maintained for fraud prevention', 'type': 'textarea'},
            {'key': '13l_fraud_prevention_monitoring', 'label': '13l. How you monitor effectiveness of fraud prevention program', 'type': 'textarea'},
        ],
    },
    {
        'title': 'Section 14: Trace back and Mass Balance',
        'fields': [
            {'type': 'static', 'text': 'No fields — informational section explaining trace-back and mass-balance audits performed during the on-site inspection.'},
        ],
    },
    {
        'title': 'Section 15: Affirmation',
        'fields': [
            {'type': 'static', 'text': 'I affirm that all statements made in this application are true and correct. No prohibited products have been applied to any of my organically managed fields during the three-year period prior to projected harvest. Electronic signature is accepted.'},
            {'key': '15_name', 'label': 'Name of Person completing this OSP', 'type': 'text'},
            {'key': '15_signature', 'label': 'Signature of Authorized Person', 'type': 'text'},
            {'key': '15_date', 'label': 'Date', 'type': 'date'},
        ],
    },
]
