from . import paa_auditor_qualification_top
from . import asignment_auditor
from . import paa_asignment_auditor_scheme
from . import paa_schemes_ranking
from . import res_city
from . import purchase_order
from . import res_partner
from . import product_category
from . import paa_auditor_assignment_weighting
from . import paa_audit_quantity_month
from . import paa_audit_honorarium_month
from . import paa_configuration_audit_quantity
from . import paa_configuration_audit_honorarium
from . import paa_auditor_qualification
#from . import service_referral_agreement_audit_fees